---
title: "Look into markov chains"
output:
  pdf_document: default
  html_notebook: default
---


```{r}
rand <- sample(1:3, 100, replace=TRUE)
hist(rand)

norm <- as.integer(rnorm(100,mean=2, sd=1))

unif <- as.integer(runif(100, min=1, max=4))
```

```{r}
library(markovchain)

mcWeather <- new("markovchain", states=c("sunny","cloudy","rain"), transitionMatrix = matrix(data=c(0.70,0.2,0.1, 0.3,0.4,0.3,0.2,0.45,0.35),byrow=T, nrow=3),name="Weather")

weatherOfDays <- rmarkovchain(n=365, object=mcWeather, t0="sunny")


tmp <- markovchainFit(data=weatherOfDays, method="mle", name = "Weather MLE")

plot(mcWeather)
plot(tmp$estimate)

mcWeather
tmp$estimate

test <- markovchainFit(data=rand, method="mle", name="Bird jumping")
plot(test$estimate)

test2 <- markovchainFit(data=norm, method="mle", name="normal birds")
plot(test2$estimate)

test3 <- markovchainFit(data=unif, method="mle", name="uniform birds")
plot(test3$estimate)

```

```{r, overall 6928 markov chain}
six_nine_two_eight <- read.csv("6928.csv")

six_nine_two_eight["DateTime"] <- as.POSIXct(six_nine_two_eight$access, origin="1970-01-01", tz="GMT")

six_nine_two_eight_uniq <-subset(six_nine_two_eight, subzone!="test")

unique(six_nine_two_eight_uniq$subzone)

test <- markovchainFit(data=six_nine_two_eight_uniq$subzone, method="mle", name="Tag number 6928 overal")
test
plot(test$estimate)

```

```{r, function to calc transitions}
sep_bird_id_xts <- function(samp_name, samp_id,cage_obj){
  
  raw_sample_tab <- subset(cage_obj, tagname==samp_id)
  
  xts_object <- xts(raw_sample_tab ,order.by = raw_sample_tab$DateTime)
  
  result <- list("name" = samp_name, "ID"=samp_id, "xts_obj"=xts_object)
  return(result)
}

sep_bird_id_period <- function(samp_name, samp_id, cage_obj, cutoff){
  
  raw_sample_tab <- subset(cage_obj, tagname==samp_id)
  
  xts_object <- xts(raw_sample_tab ,order.by=raw_sample_tab$DateTime)
  
  xts_object <- xts_object[cutoff]
  
  daily <- to.daily(xts_object$subzone, OHLC=F,)
  weekly <- to.weekly(xts_object$subzone, OHLC=F)
  monthly <- to.monthly(xts_object$subzone, OHLC=F)
  index(monthly) <-as.POSIXct(index(monthly))
  
  result <- list("name" = samp_name, "ID"=samp_id, "xts_obj"=xts_object, "daily_obj"=daily,
                 "weekly_obj"=weekly, "monthly_obj"=monthly)
  return(result)
}

#input a sample name
#returns a vector labeled with sample name, and bottom, middle, top and total transitions

calc_trans<- function(samp_name,samp_obj, id){
  bottom_trans <-0
  mid_trans<-0
  top_trans<-0
  trans<-0
  count <- 0
  
  for (i in 2:length(samp_obj$subzone)) {
  previous_state <- as.character(samp_obj$subzone[i-1])
  current_state <- as.character(samp_obj$subzone[i])
  
  #print(paste(previous_state,":",current_state))
  
  
  if (previous_state == current_state) {
    count <- count+1
  }
  else{
    
    if(current_state == "bottom" || current_state == "Bottom"){
      bottom_trans <- bottom_trans+1
      trans<- trans+1
    }
    if (current_state=="middle" || current_state == "Middle") {
      mid_trans <- mid_trans+1
      trans <- trans+1
    }
    if(current_state =="top" || current_state=="Top"){
      top_trans <- top_trans+1
      trans <- trans+1
    }
  }
  }
  
  result <- c(samp_name,id,bottom_trans,mid_trans,top_trans,trans)
  return(result)
  
}

calc_trans_period<- function(samp_name, daily_indexed, raw_table,freq){
  result <- data.frame()
  
  for (i in 2:(length(daily_indexed))){
    curr_day <- raw_table[paste0(index(daily_indexed)[i-1],"/",index(daily_indexed)[i])]
    curr_day_trans <- calc_trans(paste0(samp_name,".",freq,".",i),curr_day, samp_name)
    result <- rbind(result,curr_day_trans)
    }
  colnames(result) <- c("sample","ID","bottom","mid","top","total")
  return(result)
}
```


```{r, setup zoo for six eight nine four}
library(xts)

six_eight_nine_four <- read.csv("6894.csv")

bird_ids_6894 <- na.trim(unique(six_eight_nine_four$tagname))
bird_ids_6894 <- sort(bird_ids_6894)

six_eight_nine_four <- six_eight_nine_four[order(six_eight_nine_four$access),] 

six_eight_nine_four["DateTime"] <- as.POSIXct(six_eight_nine_four$access, origin="1970-01-01", tz="GMT")

unique(six_eight_nine_four$subzone)

six_eight_nine_four$subzone[six_eight_nine_four$subzone == "M"] <- "middle"
six_eight_nine_four$subzone[six_eight_nine_four$subzone == "B"] <- "bottom"
six_eight_nine_four$subzone[six_eight_nine_four$subzone == "T"] <- "top"

unique(six_eight_nine_four$subzone)

sum(is.na(six_eight_nine_four$DateTime))

six_eight_nine_four <- six_eight_nine_four[!is.na(six_eight_nine_four$DateTime),]

sum(is.na(six_eight_nine_four$DateTime))

#res <- sep_bird_id(samp_name = "6894",cage_obj = six_eight_nine_four,samp_id = bird_ids_6894[1])

#generate list of XTS objects 
reslist_6894 <- list()
for(i in 1:length(bird_ids_6894)){
  
  res <- sep_bird_id_xts(samp_name="6894",cage_obj =six_eight_nine_four, samp_id = bird_ids_6894[i])
  reslist_6894[[i]] <- res
}

# #summarize the xts objects to find a period of time that 
# for(item in reslist_6894){
#   print(item$ID)
#   print(summary(item$xts_obj))
# }

remove <- c("6862","6880","6881","9023","9038","9042","9050","9059")
bird_ids_6894_new <- bird_ids_6894 [! bird_ids_6894  %in% remove ]
#generate list of the first 10 truncated XTS objects
reslist2_6894 <- list()
for(i in 1:length(bird_ids_6894_new)){
  res <- sep_bird_id_period(samp_name="6894",cage_obj =six_eight_nine_four, samp_id = bird_ids_6894_new[i],cutoff = "2020-12-02 23:00:00/2021-02-18 10:00:00")
  reslist2_6894[[i]] <- res
}

# #summarize the xts objects to check that the truncation worked
# for(item in reslist2_6894){
#   print(item$ID)
#   print(summary(item$xts_obj))
#   print(item$daily_obj)
# }

#find wholly non-na daily timeset, to be able to feed into the transcalc
big_table_6894 <- reslist2_6894[[1]]$daily_obj
for(i in 2:length(reslist2_6894)){
  current <- reslist2_6894[[i]]$daily_obj
  big_table_6894 <- cbind(big_table_6894,current)
}
print(sum(is.na(big_table_6894)))
print(head(big_table_6894))

remove <- c("6862","6880","6881","6882","6887","6891","6892","6893","6894","6900","9059","9023")
bird_ids_6894_new_2 <- bird_ids_6894 [! bird_ids_6894  %in% remove ]
#generate list of the first 10 truncated XTS objects
reslist3_6894 <- list()
for(i in 1:length(bird_ids_6894_new_2)){
  res <- sep_bird_id_period(samp_name="6894",cage_obj =six_eight_nine_four, samp_id = bird_ids_6894_new_2[i],cutoff = "2021-02-18 T16:00:00/2021-05-05 T23:00:00")
  reslist3_6894[[i]] <- res
}

#find wholly non-na daily timeset, to be able to feed into the transcalc
big_table_2_6894 <- reslist3_6894[[1]]$daily_obj
for(i in 2:length(reslist3_6894)){
  current <- reslist3_6894[[i]]$daily_obj
  big_table_2_6894 <- cbind(big_table_2_6894,current)
}
print(big_table_2_6894)

#summary(res$xts_obj)

#xts_6894 <- xts(six_eight_nine_four,order.by = six_eight_nine_four$DateTime)

#summary(xts_6894)

#daily_6894 <- to.daily(xts_6894$subzone, OHLC=F,)
#weekly_6894 <- to.weekly(xts_6894$subzone, OHLC=F)
#monthly_6894 <- to.monthly(xts_6894$subzone, OHLC=F)
#index(monthly_6894) <-as.POSIXct(index(monthly_6894))

#length(daily_6894)

#six_eight_nine_four_daily <- calc_trans_period("6894",daily_6894,xts_6894,"d")

#six_eight_nine_four_weekly <- calc_trans_period("6894",weekly_6894,xts_6894,"w")

#six_eight_nine_four_monthly <- calc_trans_period("6894",monthly_6894,xts_6894,"m")

# #TODO fix these write calls once the data is concated
# write.csv(six_eight_nine_four_daily,"6894_daily.csv",row.names = F)
# write.csv(six_eight_nine_four_weekly,"6894_weekly.csv",row.names=F)
# write.csv(six_eight_nine_four_monthly,"6894_monthly.csv",row.names=F)
```


```{r, generate transiton tables for 6928}
#65530
six_nine_two_eight <- read.csv("6928.csv")

bird_ids_6928 <- na.trim(unique(six_nine_two_eight$tagname))
bird_ids_6928 <- sort(bird_ids_6928)

six_nine_two_eight["DateTime"] <- as.POSIXct(six_nine_two_eight$access, origin="1970-01-01", tz="GMT")

unique(six_nine_two_eight$subzone)

six_nine_two_eight$subzone[six_nine_two_eight$subzone == "Bottom"] <- "bottom"
six_nine_two_eight$subzone[six_nine_two_eight$subzone == "middle"] <- "middle"
six_nine_two_eight$subzone[six_nine_two_eight$subzone == "Top"] <- "top"
six_nine_two_eight <-subset(six_nine_two_eight, subzone!="test")
#65475
unique(six_nine_two_eight$subzone)

sum(is.na(six_nine_two_eight$DateTime))
sum(is.na(six_nine_two_eight$subzone))

#generate list of XTS objects 
reslist_6928 <- list()
for(i in 1:length(bird_ids_6928)){
  
  res <- sep_bird_id_xts(samp_name="6928",cage_obj =six_nine_two_eight, samp_id = bird_ids_6928[i])
  reslist_6928[[i]] <- res
}

# #summarize the xts objects to find a period of time that 
# for(item in reslist_6928){
#   print(item$ID)
#   print(summary(item$xts_obj))
# }

remove <- c("6941","6974","9009","9011","9023")
bird_ids_6928_new <- bird_ids_6928 [! bird_ids_6928  %in% remove ]
#generate list of the first 10 truncated XTS objects
reslist2_6928 <- list()
for(i in 1:length(bird_ids_6928_new)){
  res <- sep_bird_id_period(samp_name="6928",cage_obj =six_nine_two_eight, samp_id = bird_ids_6928_new[i],cutoff = "2021-02-18 T16:00:00/2021-05-05 T23:00:00")
  reslist2_6928[[i]] <- res
}

# #summarize the xts objects to check that the truncation worked
# for(item in reslist2_6928){
#   print(item$ID)
#   print(summary(item$xts_obj))
#   print(item$daily_obj)
# }

#find wholly non-na daily timeset, to be able to feed into the transcalc
big_table_6928 <- reslist2_6928[[1]]$daily_obj
for(i in 2:length(reslist2_6928)){
  current <- reslist2_6928[[i]]$daily_obj
  big_table_6928 <- cbind(big_table_6928,current)
}
print(sum(is.na(big_table_6928)))

# xts_6928 <- xts(six_nine_two_eight,order.by = six_nine_two_eight$DateTime)
# 
# summary(xts_6928)
# 
# daily_6928 <- to.daily(xts_6928$subzone, OHLC=F,)
# weekly_6928 <- to.weekly(xts_6928$subzone, OHLC=F)
# monthly_6928 <- to.monthly(xts_6928$subzone, OHLC=F)
# index(monthly_6928) <-as.POSIXct(index(monthly_6928))
# 
# length(daily_6928)

#six_nine_two_eight_daily <- calc_trans_period("6928",daily_6928,xts_6928,"d")

#six_nine_two_eight_weekly <- calc_trans_period("6928",weekly_6928,xts_6928,"w")

#six_nine_two_eight_monthly <- calc_trans_period("6928",monthly_6928,xts_6928,"m")

#write.csv(six_nine_two_eight_daily,"6928_daily.csv",row.names = F)
#write.csv(six_nine_two_eight_weekly,"6928_weekly.csv",row.names=F)
#write.csv(six_nine_two_eight_monthly,"6928_monthly.csv",row.names=F)

```


```{r, generate transition tables for 6988}
#65524
six_nine_eight_eight <- read.csv("6988.csv")

bird_ids_6988 <- unique(six_nine_eight_eight$tagname)
bird_ids_6988 <- na.trim(sort(bird_ids_6988))

six_nine_eight_eight["DateTime"] <- as.POSIXct(six_nine_eight_eight$access, origin="1970-01-01", tz="GMT")

unique(six_nine_eight_eight$subzone)

six_nine_eight_eight$subzone[six_nine_eight_eight$subzone == "Bottom"] <- "bottom"
six_nine_eight_eight$subzone[six_nine_eight_eight$subzone == "Middle"] <- "middle"
six_nine_eight_eight$subzone[six_nine_eight_eight$subzone == "Top"] <- "top"

#65475
unique(six_nine_eight_eight$subzone)

sum(is.na(six_nine_eight_eight$DateTime))
sum(is.na(six_nine_eight_eight$subzone))


#generate list of XTS objects 
reslist_6988 <- list()
for(i in 1:length(bird_ids_6988)){
  
  res <- sep_bird_id_xts(samp_name="6988",cage_obj =six_nine_eight_eight, samp_id = bird_ids_6988[i])
  reslist_6988[[i]] <- res
}

# #summarize the xts objects to find a period of time that 
# for(item in reslist_6988){
#   print(item$ID)
#   print(summary(item$xts_obj))
# }

remove <- c("6910","6914","9005")
bird_ids_6988_new <- bird_ids_6988 [! bird_ids_6988  %in% remove ]
#generate list of the first 10 truncated XTS objects
reslist2_6988 <- list()
for(i in 1:length(bird_ids_6988_new)){
  res <- sep_bird_id_period(samp_name="6988",cage_obj =six_nine_eight_eight, samp_id = bird_ids_6988_new[i],cutoff = "2021-02-18 T16:00:00/2021-05-05 T23:00:00")
  reslist2_6988[[i]] <- res
}

# #summarize the xts objects to check that the truncation worked
# for(item in reslist2_6988){
#   print(item$ID)
#   print(summary(item$xts_obj))
#   print(item$daily_obj)
# }

#find wholly non-na daily timeset, to be able to feed into the transcalc
big_table_6988 <- reslist2_6988[[1]]$daily_obj
for(i in 2:length(reslist2_6988)){
  current <- reslist2_6988[[i]]$daily_obj
  big_table_6988 <- cbind(big_table_6988,current)
}
print(sum(is.na(big_table_6988)))

sum(is.na(cbind(big_table_2_6894,big_table_6928,big_table_6988)))

# xts_6988 <- xts(six_nine_eight_eight,order.by = six_nine_eight_eight$DateTime)
# 
# summary(xts_6988)
# 
# daily_6988 <- to.daily(xts_6988$subzone, OHLC=F,)
# weekly_6988 <- to.weekly(xts_6988$subzone, OHLC=F)
# monthly_6988 <- to.monthly(xts_6988$subzone, OHLC=F)
# index(monthly_6988) <-as.POSIXct(index(monthly_6988))
# 
# length(daily_6988)
# 
# six_nine_eight_eight_daily <- calc_trans_period("6988",daily_6988,xts_6988,"d")
# 
# six_nine_eight_eight_weekly <- calc_trans_period("6988",weekly_6988,xts_6988,"w")
# 
# six_nine_eight_eight_monthly <- calc_trans_period("6988",monthly_6988,xts_6988,"m")
# 
# write.csv(six_nine_eight_eight_daily,"6988_daily.csv",row.names = F)
# write.csv(six_nine_eight_eight_weekly,"6988_weekly.csv",row.names=F)
# write.csv(six_nine_eight_eight_monthly,"6988_monthly.csv",row.names=F)

```

```{r}
#65495
nine_zero_one_three <- read.csv("9013.csv")

bird_ids_9013 <- unique(nine_zero_one_three$tagname)
bird_ids_9013 <- na.trim(sort(bird_ids_9013))

nine_zero_one_three["DateTime"] <- as.POSIXct(nine_zero_one_three$access, origin="1970-01-01", tz="GMT")

unique(nine_zero_one_three$subzone)

nine_zero_one_three$subzone[nine_zero_one_three$subzone == "Bottom"] <- "bottom"
nine_zero_one_three$subzone[nine_zero_one_three$subzone == "Middle"] <- "middle"
nine_zero_one_three$subzone[nine_zero_one_three$subzone == "Top"] <- "top"

#65495
unique(nine_zero_one_three$subzone)

sum(is.na(nine_zero_one_three$DateTime))
sum(is.na(nine_zero_one_three$subzone))


#generate list of XTS objects 
reslist_9013 <- list()
for(i in 1:length(bird_ids_9013)){
  
  res <- sep_bird_id_xts(samp_name="9013",cage_obj =nine_zero_one_three, samp_id = bird_ids_9013[i])
  reslist_9013[[i]] <- res
}

# #summarize the xts objects to find a period of time that 
# for(item in reslist_9013){
#   print(item$ID)
#   print(summary(item$xts_obj))
# }

remove <- c("6998")
bird_ids_9013_new <- bird_ids_9013 [! bird_ids_9013  %in% remove ]
#generate list of the first 10 truncated XTS objects
reslist2_9013 <- list()
for(i in 1:length(bird_ids_9013_new)){
  res <- sep_bird_id_period(samp_name="9013",cage_obj =nine_zero_one_three, samp_id = bird_ids_9013_new[i],cutoff = "2021-03-11 T18:00:00/2021-05-07 T17:00:00")
  reslist2_9013[[i]] <- res
}

# #summarize the xts objects to check that the truncation worked
# for(item in reslist2_9013){
#   print(item$ID)
#   print(summary(item$xts_obj))
#   print(item$daily_obj)
# }

#find wholly non-na daily timeset, to be able to feed into the transcalc
big_table_9013 <- reslist2_9013[[1]]$daily_obj
for(i in 2:length(reslist2_9013)){
  current <- reslist2_9013[[i]]$daily_obj
  big_table_9013 <- cbind(big_table_9013,current)
}
print(sum(is.na(big_table_9013)))

sum(is.na(cbind(big_table_2_6894,big_table_6928,big_table_6988)))
# 
# xts_9013 <- xts(nine_zero_one_three,order.by = nine_zero_one_three$DateTime)
# 
# summary(xts_9013)
# 
# daily_9013 <- to.daily(xts_9013$subzone, OHLC=F,)
# weekly_9013 <- to.weekly(xts_9013$subzone, OHLC=F)
# monthly_9013 <- to.monthly(xts_9013$subzone, OHLC=F)
# index(monthly_9013) <-as.POSIXct(index(monthly_9013))
# 
# length(daily_9013)
# 
# nine_zero_one_three_daily <- calc_trans_period("9013",daily_9013,xts_9013,"d")
# 
# nine_zero_one_three_weekly <- calc_trans_period("9013",weekly_9013,xts_9013,"w")
# 
# nine_zero_one_three_monthly <- calc_trans_period("9013",monthly_9013,xts_9013,"m")
# 
# write.csv(nine_zero_one_three_daily,"9013_daily.csv",row.names = F)
# write.csv(nine_zero_one_three_weekly,"9013_weekly.csv",row.names=F)
# write.csv(nine_zero_one_three_monthly,"9013_monthly.csv",row.names=F)


```


```{r, calc trans on bird blocks}
trans_reslist_6894_dec <- list()
for(i in 1:length(reslist2_6894)){
  
  daily_trans_table <- calc_trans_period(reslist2_6894[[i]]$ID,reslist2_6894[[i]]$daily_obj,reslist2_6894[[i]]$xts_obj,"d")
  weekly_trans_table <- calc_trans_period(reslist2_6894[[i]]$ID,reslist2_6894[[i]]$weekly_obj,reslist2_6894[[i]]$xts_obj,"w")
  monthly_trans_table <- calc_trans_period(reslist2_6894[[i]]$ID,reslist2_6894[[i]]$monthly_obj,reslist2_6894[[i]]$xts_obj,"m")
    
  result <- list("name"=reslist2_6894[[i]]$ID,"daily"=daily_trans_table, "weekly"=weekly_trans_table,"monthly"=monthly_trans_table, "raw"=reslist2_6894[[i]]$xts_obj)
  trans_reslist_6894_dec[[i]] <- result
}

trans_reslist_6894_dec

december_to_feb_daily <- data.frame()
december_to_feb_weekly <- data.frame()
december_to_feb_monthly <- data.frame()
#TODO select sample as opposed to ID for intra bird comparison (alpha eq)
for(item in trans_reslist_6894_dec){
  december_to_feb_daily <- rbind(december_to_feb_daily, item$daily[c("ID","bottom","mid","top","total")])
  december_to_feb_weekly <- rbind(december_to_feb_weekly, item$weekly[c("ID","bottom","mid","top","total")])
  december_to_feb_monthly <- rbind(december_to_feb_monthly, item$monthly[c("ID","bottom","mid","top","total")])
}

write.csv(december_to_feb_daily,"december_to_feb_daily.csv",row.names = F)
write.csv(december_to_feb_weekly,"december_to_feb_weekly.csv",row.names = F)
write.csv(december_to_feb_monthly,"december_to_feb_monthly.csv",row.names = F)


```


```{r, work with the 2-18 datasets}

whole_data_sanity <- data.frame()
whole_data_sanity <- reslist3_6894[[1]]$daily_obj
for(item in reslist3_6894){
  whole_data_sanity <- cbind(whole_data_sanity,item$daily_obj)
}
for(item in reslist2_6928){
  whole_data_sanity <- cbind(whole_data_sanity, item$daily_obj)
}
for(item in reslist2_6988){
  whole_data_sanity <- cbind(whole_data_sanity, item$daily_obj)
}

#yay the data is whole
sum(is.na(whole_data_sanity))

trans_reslist_feb <- list()
for(i in 1:length(reslist3_6894)){
  
  daily_trans_table <- calc_trans_period(reslist3_6894[[i]]$ID,reslist3_6894[[i]]$daily_obj,reslist3_6894[[i]]$xts_obj,"d")
  weekly_trans_table <- calc_trans_period(reslist3_6894[[i]]$ID,reslist3_6894[[i]]$weekly_obj,reslist3_6894[[i]]$xts_obj,"w")
  monthly_trans_table <- calc_trans_period(reslist3_6894[[i]]$ID,reslist3_6894[[i]]$monthly_obj,reslist3_6894[[i]]$xts_obj,"m")
    
  result <- list("ID"=reslist3_6894[[i]]$ID,"daily"=daily_trans_table, "weekly"=weekly_trans_table,"monthly"=monthly_trans_table, "raw"=reslist3_6894[[i]]$xts_obj)
  trans_reslist_feb[[i]] <- result
}
#trans_reslist_feb

for(i in 1:length(reslist2_6928)){
  
  daily_trans_table <- calc_trans_period(reslist2_6928[[i]]$ID,reslist2_6928[[i]]$daily_obj,reslist2_6928[[i]]$xts_obj,"d")
  weekly_trans_table <- calc_trans_period(reslist2_6928[[i]]$ID,reslist2_6928[[i]]$weekly_obj,reslist2_6928[[i]]$xts_obj,"w")
  monthly_trans_table <- calc_trans_period(reslist2_6928[[i]]$ID,reslist2_6928[[i]]$monthly_obj,reslist2_6928[[i]]$xts_obj,"m")
    
  result <- list("ID"=reslist2_6928[[i]]$ID,"daily"=daily_trans_table, "weekly"=weekly_trans_table,"monthly"=monthly_trans_table, "raw"=reslist2_6928[[i]]$xts_obj)
  trans_reslist_feb[[i+4]] <- result
}



for(i in 1:length(reslist2_6988)){
  
  daily_trans_table <- calc_trans_period(reslist2_6988[[i]]$ID,reslist2_6988[[i]]$daily_obj,reslist2_6988[[i]]$xts_obj,"d")
  weekly_trans_table <- calc_trans_period(reslist2_6988[[i]]$ID,reslist2_6988[[i]]$weekly_obj,reslist2_6988[[i]]$xts_obj,"w")
  monthly_trans_table <- calc_trans_period(reslist2_6988[[i]]$ID,reslist2_6988[[i]]$monthly_obj,reslist2_6988[[i]]$xts_obj,"m")
    
  result <- list("ID"=reslist2_6988[[i]]$ID,"daily"=daily_trans_table, "weekly"=weekly_trans_table,"monthly"=monthly_trans_table, "raw"=reslist2_6988[[i]]$xts_obj)
  trans_reslist_feb[[i+24]] <- result
}


feb_to_may_daily <- data.frame()
feb_to_may_weekly <- data.frame()
feb_to_may_monthly <- data.frame()
#TODO select sample as opposed to ID for intra bird comparison (alpha eq)
for(item in trans_reslist_feb){
  feb_to_may_daily <- rbind(feb_to_may_daily, item$daily[c("ID","bottom","mid","top","total")])
  feb_to_may_weekly <- rbind(feb_to_may_weekly, item$weekly[c("ID","bottom","mid","top","total")])
  feb_to_may_monthly <- rbind(feb_to_may_monthly, item$monthly[c("ID","bottom","mid","top","total")])
}


write.csv(feb_to_may_daily,"feb_to_may_daily.csv",row.names = F)
write.csv(feb_to_may_weekly,"feb_to_may_weekly.csv",row.names = F)
write.csv(feb_to_may_monthly,"feb_to_may_monthly.csv",row.names = F)
```



```{r, make the march dataset}

whole_data_sanity <- data.frame()
whole_data_sanity <- reslist2_9013[[1]]$daily_obj
for(item in reslist2_9013){
  whole_data_sanity <- cbind(whole_data_sanity,item$daily_obj)
}

raw_9005 <- reslist_6988[[11]]$xts_obj
res_9005 <- raw_9005["2021-03-11 T18:00:00/2021-05-07 T17:00:00"]
daily <- to.daily(res_9005$subzone, OHLC=F,)
weekly <- to.weekly(res_9005$subzone, OHLC=F)
monthly <- to.monthly(res_9005$subzone, OHLC=F)
index(monthly) <-as.POSIXct(index(monthly))
result <- list("name" ="6988", "ID"="9005", "xts_obj"=res_9005, "daily_obj"=daily,
                 "weekly_obj"=weekly, "monthly_obj"=monthly)
daily_9005 <- daily
weekly_9005 <- weekly
monthly_9005<- monthly
whole_data_sanity <- cbind(whole_data_sanity, result$daily)

raw_6941 <- reslist_6928[[8]]$xts_obj
res_6941 <- raw_6941["2021-03-11 T18:00:00/2021-05-07 T17:00:00"]
daily <- to.daily(res_6941$subzone, OHLC=F,)
weekly <- to.weekly(res_6941$subzone, OHLC=F)
monthly <- to.monthly(res_6941$subzone, OHLC=F)
index(monthly) <-as.POSIXct(index(monthly))
result <- list("name" ="6928", "ID"="6941", "xts_obj"=res_6941, "daily_obj"=daily,
                 "weekly_obj"=weekly, "monthly_obj"=monthly)
daily_6941 <- daily
weekly_6941 <- weekly
monthly_6941 <- monthly
whole_data_sanity <- cbind(whole_data_sanity, result$daily)

#yay the data is whole
sum(is.na(whole_data_sanity))

#calculate transition tables for the dataset in cage 9013
trans_reslist_mar <- list()
for(i in 1:length(reslist2_9013)){
  daily_trans_table <- calc_trans_period(reslist2_9013[[i]]$ID,reslist2_9013[[i]]$daily_obj,reslist2_9013[[i]]$xts_obj,"d")
  weekly_trans_table <- calc_trans_period(reslist2_9013[[i]]$ID,reslist2_9013[[i]]$weekly_obj,reslist2_9013[[i]]$xts_obj,"w")
  monthly_trans_table <- calc_trans_period(reslist2_9013[[i]]$ID,reslist2_9013[[i]]$monthly_obj,reslist2_9013[[i]]$xts_obj,"m")
  
  result <- list("ID"=reslist2_9013[[i]]$ID,"daily"=daily_trans_table, "weekly"=weekly_trans_table,"monthly"=monthly_trans_table, "raw"=reslist2_9013[[i]]$xts_obj)
  trans_reslist_mar[[i]] <- result
}

#calculate transition tables for sample 9005
daily_trans_table <- calc_trans_period("9005",daily_9005,raw_9005,"d")
weekly_trans_table <- calc_trans_period("9005",weekly_9005,raw_9005,"w")
  monthly_trans_table <- calc_trans_period("9005",monthly_9005,raw_9005,"m")
  
result <- list("ID"="9005","daily"=daily_trans_table, "weekly"=weekly_trans_table,"monthly"=monthly_trans_table, "raw"=raw_9005)
trans_reslist_mar[[1+length(reslist2_9013)]] <- result

#calculate transition tables for sample 6941
daily_trans_table <- calc_trans_period("6941",daily_6941,raw_6941,"d")
weekly_trans_table <- calc_trans_period("6941",weekly_6941,raw_6941,"w")
  monthly_trans_table <- calc_trans_period("6941",monthly_6941,raw_6941,"m")
  
result <- list("ID"="6941","daily"=daily_trans_table, "weekly"=weekly_trans_table,"monthly"=monthly_trans_table, "raw"=raw_6941)
trans_reslist_mar[[length(reslist2_9013)+2]] <- result

#concat all transtition tables into one large 
mar_to_may_daily <- data.frame()
mar_to_may_weekly <- data.frame()
mar_to_may_monthly <- data.frame()
#TODO select sample as opposed to ID for intra bird comparison (alpha eq)
for(item in trans_reslist_mar){
  mar_to_may_daily <- rbind(mar_to_may_daily, item$daily[c("ID","bottom","mid","top","total")])
  mar_to_may_weekly <- rbind(mar_to_may_weekly, item$weekly[c("ID","bottom","mid","top","total")])
  mar_to_may_monthly <- rbind(mar_to_may_monthly, item$monthly[c("ID","bottom","mid","top","total")])
}


write.csv(mar_to_may_daily,"mar_to_may_daily.csv",row.names = F)
write.csv(mar_to_may_weekly,"mar_to_may_weekly.csv",row.names = F)
write.csv(mar_to_may_monthly,"mar_to_may_monthly.csv",row.names = F)

```



```{r, try out LDA with the Iris example}
library(MASS)
Iris <- data.frame(rbind(iris3[,,1], iris3[,,2], iris3[,,3]),Sp = rep(c("s","c","v"), rep(50,3)))
train <- sample(1:150, 75)
table(Iris$Sp[train])

z <- lda(Sp ~ ., Iris, prior = c(1,1,1)/3, subset = train)
predict(z, Iris[-train, ])$class

(z1 <- update(z, . ~ . - Petal.W.))


```

```{r}
set.seed(34716)
library(MASS)
# 32 classes
length(unique(feb_to_may_daily$ID))
# 2432 observations/days
length(feb_to_may_daily$bottom)

feb_to_may_daily_shuff <- feb_to_may_daily[sample(1:nrow(feb_to_may_daily)),]

sample <- sample.int(n = nrow(feb_to_may_daily_shuff), size = floor(.70*nrow(feb_to_may_daily_shuff)), replace = F)
train <- feb_to_may_daily[sample, ]
test  <- feb_to_may_daily[-sample, ]

# pretty even data distribution
table(train$ID)

train_df <- as.data.frame(train)
train_df[,2:5] <- sapply(train_df[,2:5], as.numeric)
test_df <- as.data.frame(test)
test_df[,2:5] <- sapply(test_df[,2:5],as.numeric)

#TODO make a model with just top and bottom as transition zones
formula_two <- as.formula("ID ~ total")
formula_three <- as.formula("ID ~ bottom + mid + top")
formual_four <- as.formula("ID ~ bottom + mid + top + total")

mod_total <- lda(formula_two, train_df)

#variables are collinear
mod_three <- lda(formula_three, train_df)

#variables are collinear
mod_all <- lda(formual_four, train_df)

total_preds <- predict(mod_total, test_df)

three_preds <- predict(mod_three, test_df)

all_preds <- predict(mod_all, test_df)

total_preds_post <- as.data.frame(total_preds$posterior)
pred <- prediction(total_preds_post[,2],test_df$ID)

```


```{r, use Vegan to check assumptions about the data}
library(vegan)
library(moments)
library(outliers)
set.seed(34716)
library(MASS)
# 32 classes
length(unique(feb_to_may_daily$ID))
# 2432 observations/days
length(feb_to_may_daily$bottom)

feb_to_may_daily_shuff <- feb_to_may_daily[sample(1:nrow(feb_to_may_daily)),]

sample <- sample.int(n = nrow(feb_to_may_daily_shuff), size = floor(.70*nrow(feb_to_may_daily_shuff)), replace = F)
train <- feb_to_may_daily[sample, ]
test  <- feb_to_may_daily[-sample, ]

# pretty even data distribution
table(train$ID)

train_df <- as.data.frame(train)
train_df[,2:5] <- sapply(train_df[,2:5], as.numeric)
test_df <- as.data.frame(test)
test_df[,2:5] <- sapply(test_df[,2:5],as.numeric)

feb_to_may_daily <- as.data.frame(feb_to_may_daily)
feb_to_may_daily[,2:5] <- sapply(feb_to_may_daily[,2:5], as.numeric)

four_hle <- decostand(as.matrix(feb_to_may_daily[,2:5]),"hellinger")
gr <- cutree(hclust(vegdist(four_hle,"euc"),"ward.D"), 2)

four_pars <- as.matrix(feb_to_may_daily[,2:5])
four_pars.d <- dist(four_pars)
(four_HMV <- betadisper(four_pars.d, gr))
anova(four_HMV)
permutest(four_HMV)

skewness(feb_to_may_daily[2:5])

boxplot(feb_to_may_daily[2])
boxplot(feb_to_may_daily[3])
boxplot(feb_to_may_daily[4])
boxplot(feb_to_may_daily[5])

outliers::outlier(feb_to_may_daily[2])
outliers::outlier(feb_to_may_daily[3])
outliers::outlier(feb_to_may_daily[4])
outliers::outlier(feb_to_may_daily[5])

which(feb_to_may_daily[2] >= 28 | feb_to_may_daily[2] < .01 )

summary(feb_to_may_daily[,2])
```

```{r, PCA pivot}
library(REdaS)
library(vegan)
library(reshape)
library(eigenprcomp)


feb_to_may_daily <- as.data.frame(feb_to_may_daily)
feb_to_may_daily[,2:5] <- sapply(feb_to_may_daily[,2:5], as.numeric)

KMOS(feb_to_may_daily[,2:4])

bart_spher(feb_to_may_daily[,2:4])

plot(feb_to_may_daily[,2:4])

feb_to_may_daily_pca <- rda(feb_to_may_daily[,2:4],scale=T)
eig <- feb_to_may_daily_pca$CA$eig
variance <- eig*100/sum(eig)
cumvar <- cumsum(variance)
eig.pca <- data.frame(eig = eig, variance=variance, cumvariance= cumvar)
boot_pr_comp(as.matrix(feb_to_may_daily[,2:4]))

biplot(feb_to_may_daily_pca,display = c("sites","species"),type = c("text","points")) 
ordihull(feb_to_may_daily_pca, group=feb_to_may_daily$ID)


#min max normalize 
min_max_norm <- function(x){
  (x - min(x)) /(max(x)-min(x))
}

feb_to_may_daily_norm <- as.data.frame(lapply(feb_to_may_daily[,2:4], min_max_norm))
feb_to_may_daily_norm$ID <- feb_to_may_daily$ID
feb_to_may_daily_norm

plot(density(feb_to_may_daily_norm[,1]))
plot(density(feb_to_may_daily_norm[,2]))
plot(density(feb_to_may_daily_norm[,3]))

feb_to_may_daily_standard <- as.data.frame(scale(feb_to_may_daily[,2:4]))
feb_to_may_daily_standard$ID <- feb_to_may_daily$ID

plot(density(feb_to_may_daily_standard[,1]))
plot(density(feb_to_may_daily_standard[,2]))
plot(density(feb_to_may_daily_standard[,3]))

hist(feb_to_may_daily_standard[,1])
hist(feb_to_may_daily_standard[,2])
hist(feb_to_may_daily_standard[,3])

hist(feb_to_may_daily[,2],nclass = 30)
hist(feb_to_may_daily[,3])
hist(feb_to_may_daily[,4])

qnorm(feb_to_may_daily[,2:4])
```


```{r, use bestnormalize }
library(bestNormalize)
library(BBmisc)

(arcsinh_obj <- arcsinh_x(feb_to_may_daily[,2]))
#(boxcox_obj <- boxcox(feb_to_may_daily[,2]))
(yeojohnson_obj <- yeojohnson(feb_to_may_daily[,2]))
(orderNorm_obj <- orderNorm(feb_to_may_daily[,2]))
(BNobject <- bestNormalize(feb_to_may_daily[,2]))

MASS::truehist(BNobject$x.t, main="Selected Transform")

dist <- vegdist(feb_to_may_daily[,2:4],method = "gower")
clusted <- hclust(dist,method = "ward.D")
table(cutree(clusted,2))

ord <- monoMDS(dist)
plot(ord)

hist(normalize(feb_to_may_daily[,2:4],method="standardize")[,3])



```


```{r, does weekly make a difference}
library(ggfortify) 

feb_to_may_weekly <- as.data.frame(feb_to_may_weekly)
feb_to_may_weekly[,2:5] <- sapply(feb_to_may_weekly[,2:5], as.numeric)

BNobject_2 <- bestNormalize(feb_to_may_weekly[,2])
MASS::truehist(BNobject_2$x.t)
BNobject_3 <- bestNormalize(feb_to_may_weekly[,3])
MASS::truehist(BNobject_3$x.t)
BNobject_4 <- bestNormalize(feb_to_may_weekly[,4])
MASS::truehist(BNobject_4$x.t)
BNobject_5 <- bestNormalize(feb_to_may_weekly[,5])
MASS::truehist(BNobject_5$x.t)


feb_to_may_normed <- cbind(as.numeric(BNobject_2$x.t), as.numeric(BNobject_3$x.t), as.numeric(BNobject_4$x.t),as.numeric(BNobject_5$x.t),feb_to_may_weekly[,1])
colnames(feb_to_may_normed) <- c("bottom","mid","top","total","ID")

feb_to_may_normed <- as.data.frame(feb_to_may_normed)
feb_to_may_normed[,1:4] <- sapply(feb_to_may_normed[,1:4], as.numeric)
feb_to_may_normed

gr <- cutree(hclust(vegdist(feb_to_may_normed[,1:3],"euc"),"ward.D"),2)

feb_pars_d <- dist(feb_to_may_weekly[,2:4])
(feb_MHV <- betadisper(feb_pars_d,gr))
anova(feb_MHV)
permutest(feb_MHV)

feb_wk_pca <- prcomp(feb_to_may_normed[,1:4],scale. = F)

summary(feb_wk_pca)

plt <- autoplot(feb_wk_pca, data=feb_to_may_normed, color='ID')
plt

km.out<-0

km.out <- kmeans(feb_to_may_normed, 2, 20)
summary(km.out)

plot(feb_to_may_normed[,c("bottom","top")], col=km.out$cluster)

wss <- 0

for(i in 1:15){
  km.out <- kmeans(feb_to_may_normed[,1:4], centers = i, nstart=20)
  wss[i] <- km.out$tot.withinss
}


plot(1:15, wss, type="b")

hclust.complete <- hclust(dist(feb_to_may_normed),method="complete")
plot(hclust.complete)

cut.feb <- cutree(hclust.complete, k=3)
table(km.out$cluster, cut.feb)

pr.feb <- prcomp(x=feb_to_may_normed[,1:4], scale=F, center=F)
summary(pr.feb)


plot(pr.feb$x[,1:2],col=feb_to_may_normed$ID)
plot(pr.feb$x[,1:2],col=km.out$cluster)

km.out

length(feb_to_may_normed[,"ID"])
length(km.out$cluster)
```


```{r, does a single day or week dataset make more sense}
tmp <- cbind(as.character(feb_to_may_daily$ID), as.numeric(feb_to_may_daily$total))
tmp2 <- matrix(as.vector(as.numeric(tmp[,2])), nrow=32, byrow=T)
total_totals <- rowSums(tmp2)
max_tot <- max(total_totals)
most_active <- unique(tmp[,1])[total_totals == max_tot]

feb_to_may_daily <- data.frame()
feb_to_may_weekly <- data.frame()
feb_to_may_monthly <- data.frame()
#TODO select sample as opposed to ID for intra bird comparison (alpha eq)
for(item in trans_reslist_feb){
  feb_to_may_daily <- rbind(feb_to_may_daily, item$daily[c("sample","bottom","mid","top","total")])
  feb_to_may_weekly <- rbind(feb_to_may_weekly, item$weekly[c("sample","bottom","mid","top","total")])
  feb_to_may_monthly <- rbind(feb_to_may_monthly, item$monthly[c("sample","bottom","mid","top","total")])
}

feb_to_may_daily

most_active_intra_day <- feb_to_may_daily[grep(most_active,feb_to_may_daily$sample),]
most_active_intra_day <- as.data.frame(most_active_intra_day)
most_active_intra_day[,2:5] <- sapply(most_active_intra_day[,2:5], as.numeric)
boxplot(most_active_intra_day[,2:5])
hist(most_active_intra_day[,5])

wss <- 0

for(i in 1:15){
  km.out <- kmeans(most_active_intra_day[,2:4], centers = i, nstart=20)
  wss[i] <- km.out$tot.withinss
}


plot(1:15, wss, type="b")

km.out <- kmeans(most_active_intra_day[,2:4],2, 20)
summary(km.out)
km.out$cluster

pr.feb <- prcomp(x=most_active_intra_day[,2:4], scale=T, center=T)
summary(pr.feb)


plot(pr.feb$x[,1:2],label=most_active_intra_day$sample)
plot(pr.feb$x[,1:2],col=km.out$cluster) +
text(pr.feb$x[,1:2], labels=most_active_intra_day$sample, cex=0.9, font =.5)

autoplot(pr.feb, col=km.out$cluster,data=most_active_intra_day, label=most_active_intra_day$sample)
ggbiplot(pr.feb, labels=most_active_intra_day$sample)

ggplot(pr.feb$x[,1:2], aes(x=PC1, y=PC2, color=as.character(km.out$cluster), label=as.character(most_active_intra_day$sample)))+geom_point() + geom_text(size=3,check_overlap = T)

cluster_table <- data.frame(cbind(as.numeric(km.out$cluster),most_active_intra_day$sample))
cluster_table[order(cluster_table$X1),]

```