---
title: "RFID Room 2"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---


# Data Preprocessing

```{r function to clean data from duplicate reads}
identify_duplicate_records <- function(records){
  records$duplicate <- rep(0, length(records$subzone))
  records <- records[order(records$accessdate),]
  
  for(i in 3:length(records$subzone)){

    primary <- records[i-2,]
    secondary <- records[i-1,]
    tertiary <- records[i,]
    #print(primary)

    #print(paste(primary$subzone," : ",secondary$subzone))
  
  
    #check if primary zone is same as secondary zone
    if(length(unique(c(primary$subzone,secondary$subzone,tertiary$subzone)))!=3){
      if(primary$subzone != secondary$subzone){
        records[[i-2,"duplicate"]] <- 1
      } else if(secondary$subzone != tertiary$subzone){
        records[[i-1,"duplicate"]] <- 1
      }
    }

  }
  return(records)
}

```

```{r from Kenis data}
# from Analyis.R generated by Keni
# calculates the proportion of time spent in each zone based on the whole time series passed in
getTimeBudgetProp <- function(data) {
  columns = c("interval","Bottom","Middle","Top") 
  TBS = data.frame(matrix(nrow = 0, ncol = length(columns))) 
  colnames(TBS) = columns

  # store inteval as minutes
  TBStag<- data.frame(t = (as.numeric(data$t2) - as.numeric(data$t1)) / 60, zone=data$to_zone)

  Interval <- c(ymd_hms(as.POSIXct.numeric(as.numeric(head(data,n=1)$t1),origin=origin)),ymd_hms(as.POSIXct.numeric(as.numeric(tail(data,n=1)$t2),origin=origin)))

  TBbot<-sum(TBStag[which(TBStag$to_zone == "bottom"),]$t)/sum(TBStag$t)
    
  TBmid<-sum(TBStag[which(TBStag$to_zone == "middle"),]$t)/sum(TBStag$t)
     
  TBtop<-sum(TBStag[which(TBStag$to_zone == "top"),]$t)/sum(TBStag$t)
     
  TBS<-matrix(c(TBbot,TBmid,TBtop),ncol=3)
     
  return(data.frame(Interval[1],Interval[2],TBS))
  
}

getTimeBudgetAbs <- function(data) {
  columns = c("Bottom","Middle","Top") 
  TBS = data.frame(matrix(nrow = 0, ncol = length(columns))) 
  colnames(TBS) = columns

  # store inteval as minutes
  TBStag<- data.frame(t = (as.numeric(data$t2) - as.numeric(data$t1)) / 60, zone=data$zone)

  TBbot<-sum(TBStag[which(TBStag$to_zone == "bottom"),]$t)
    
  TBmid<-sum(TBStag[which(TBStag$to_zone == "middle"),]$t)
     
  TBtop<-sum(TBStag[which(TBStag$to_zone == "top"),]$t)

  TBS<-matrix(c(TBbot,TBmid,TBtop),ncol=3)
     
  return(TBS)
  
}

getDayRecords <- function(data, start, end){
  data$day <- (format(data$datetime, "%H:%M") >= start & format(data$datetime, "%H:%M") < end)

  day <- data[data$day == TRUE,]

  day$date <- format(day$datetime, "%Y/%m/%d")

  date_to_day <- data.frame(cbind(unique(day$date),1:length(unique(day$date))))

  colnames(date_to_day) <- c('datetime','dos')

  day$dos <- as.numeric(date_to_day[match(format(day$datetime, "%Y/%m/%d"), date_to_day$datetime),2])

  week_offset <- as.numeric(format(day$datetime, "%-V")[1])

  day$wos <- (as.numeric(format(day$datetime, "%-V"))-week_offset)+1

  return(day)
}

getNightRecords <- function(data, start, end){

  data$day <- (format(data$datetime, "%H:%M") >= start & format(data$datetime, "%H:%M") < end)

  night <- data[data$day != TRUE,]

  night$date <- format(night$datetime, "%Y/%m/%d")

  date_to_day <- data.frame(cbind(unique(night$date),1:length(unique(night$date))))

  colnames(date_to_day) <- c('datetime','dos')

  #night$dos <- as.numeric(date_to_day[match(format(night$datetime, "%Y/%m/%d"), date_to_day$datetime),2])

  night$dos <- ifelse(hour(night$datetime) %in% c(0,1,2,3,4,5),as.numeric(date_to_day[match(format(night$datetime, "%Y/%m/%d"), date_to_day$datetime),2])-1, as.numeric(date_to_day[match(format(night$datetime, "%Y/%m/%d"), date_to_day$datetime),2]))


  #night$dos <- as.numeric(date_to_day[match(format(night$datetime, "%Y/%m/%d"), date_to_day$datetime),2])


  week_offset <- as.numeric(format(night$datetime, "%-V")[1])

  night$wos <- (as.numeric(format(night$datetime, "%-V"))-week_offset)+1

  return(night)
}

getDailyTimeBudgetProp <- function(data){



}

nestedTimeToIntervals <- function(data){
  #TODO decide how to return this and/or make a special time budget function that nests the data before it calculates the budget.
  # I'm going to remove date as the nesting function
  tmp <- data |> 
  nest(by_day = -c(dos)) |>
  mutate(daily_int = map(by_day, ~timeToIntervals(.x))) #|>
  #unnest(daily_int)

  return(tmp)
}

timeToIntervals <- function(data){
  requireNamespace("dplyr")

  interval_table <- data.frame()

  first_entry <- head(data,n=1)
  transition_into <- data[which(data$value != dplyr::lag(data$value)),]
  transition_from <- data[which(data$value != dplyr::lag(data$value))-1,]
  last_entry <- tail(data,n=1)

  if(length(transition_into$datetime) == 0){

    new_row <- cbind(ymd_hms(first_entry$datetime),ymd_hms(last_entry$datetime),NA, as.character(first_entry$value))
    interval_table <- rbind(interval_table, new_row)
    colnames(interval_table) <- c("t1","t2","from_zone","to_zone")

  } else if( length(transition_into$value) == 1){

    new_row <- cbind(ymd_hms(first_entry$datetime),ymd_hms(transition_into[1,]$datetime),NA, as.character(first_entry$value))
    interval_table <- rbind(interval_table, new_row)
    
    new_row <- cbind(ymd_hms(transition_into[1,]$datetime), ymd_hms(last_entry[1,]$datetime),as.character(transition_from[1,2]),as.character(transition_into[1,2]))
    interval_table <- rbind(interval_table, new_row)
    colnames(interval_table) <- c("t1","t2","from_zone","to_zone")

  } else if(length(transition_into$value) == 2){

    new_row <- cbind(ymd_hms(first_entry$datetime),ymd_hms(transition_into[1,]$datetime),NA, as.character(first_entry$value))
    interval_table <- rbind(interval_table, new_row)
    
    new_row <- cbind(ymd_hms(transition_into[1,]$datetime), ymd_hms(transition_into[2,]$datetime),as.character(transition_from[1,2]),as.character(transition_into[1,2]))
    interval_table <- rbind(interval_table, new_row)
    new_row <- cbind(ymd_hms(transition_into[2,]$datetime), ymd_hms(last_entry$datetime),as.character(transition_from[2,2]),as.character(last_entry[,2]))
    interval_table <- rbind(interval_table, new_row)
    colnames(interval_table) <- c("t1","t2","from_zone","to_zone")

  } else if(length(transition_into$value) > 2) {

    new_row <- cbind(ymd_hms(first_entry$datetime),ymd_hms(transition_into[1,]$datetime),NA, as.character(first_entry$value))
    interval_table <- rbind(interval_table, new_row)

    for(i in 2:length(transition_into$value)-1){
      new_row <- cbind(ymd_hms(transition_into[i,]$datetime), ymd_hms(transition_into[i+1,]$datetime),as.character(transition_from[i,2]),as.character(transition_into[i,2]))
      interval_table <- rbind(interval_table, new_row)
    }

    colnames(interval_table) <- c("t1","t2","from_zone","to_zone")
    interval_table[length(interval_table$t2),]$t2 <- last_entry$datetime

  } else {

    print("this shouldn't happen")
    exit(0)

  }

  return(interval_table)

}

getTimeBudgetPropDayNight <- function(data) {
  columns = c("interval","Bottom","Middle","Top") 
  TBS = data.frame(matrix(nrow = 0, ncol = length(columns))) 
  colnames(TBS) = columns

  # store inteval as minutes
  TBStag<- data.frame(t = (as.numeric(data$t2) - as.numeric(data$t1)) / 60, zone=data$to_zone)

  Interval <- c(ymd_hms(as.POSIXct.numeric(as.numeric(head(data,n=1)$t1),origin=origin)),ymd_hms(as.POSIXct.numeric(as.numeric(tail(data,n=1)$t2),origin=origin)))

  TBbot<-sum(TBStag[which(TBStag$zone == "bottom"),]$t)/sum(TBStag$t)
    
  TBmid<-sum(TBStag[which(TBStag$zone == "middle"),]$t)/sum(TBStag$t)
     
  TBtop<-sum(TBStag[which(TBStag$zone == "top"),]$t)/sum(TBStag$t)
     
  TBS<-matrix(c(TBbot,TBmid,TBtop),ncol=3)
     
  return(data.frame(Interval[1],Interval[2],TBS))
  
}

sliceTsibble <- function(data, start, stop){
  
  previous_state <- tail(data[data$datetime <= ymd_hms(start),],n=1)
  greater_than_start <- data[data$datetime >= ymd_hms(start),]
  less_than_end <- greater_than_start[greater_than_start$datetime <= ymd_hms(stop),]
  final_state <- head(greater_than_start[greater_than_start$datetime >= ymd_hms(stop),],n=1)


  if(nrow(less_than_end) == 0){
    less_than_end <- NA
    return(less_than_end)
  }

  previous_state$datetime <- ymd_hms(start)
  final_state$datetime <- ymd_hms(stop)
  less_than_end <- bind_rows(less_than_end, previous_state)
  less_than_end <- bind_rows(less_than_end, final_state)
  return(less_than_end)
  
}
```

```{r nice start function}

nice_start <- function(dataframe, units, interval_min){
  requireNamespace("lubridate")
  dataframe[1,1]$datetime <- round_date(ymd_hms(dataframe[1,1]$datetime), unit=units)
  attr(dataframe, 'interval') <- new_interval(min=interval_min)
  # remove duplicate entries 
  #dataframe <- dataframe[!duplicates(dataframe)]

  return(dataframe)
}

```

## Import Room 2

```{r generate transition tables for room 2}

library(xts)
library(lubridate)
library(tidyverse)
library(tidyr)
library(dplyr)
library(tsibble)


room_2 <- read.csv("../data/DK20-03-RFID-R2-febmay-080423.csv")

bird_ids_room_2 <- unique(room_2$tagname)
bird_ids_room_2 <- na.trim(sort(bird_ids_room_2))

room_2["DateTime"] <- as.POSIXct(room_2$access, origin="1970-01-01", tz="GMT")


print("what makes up subzone col")
unique(room_2$subzone)

room_2$subzone[room_2$subzone == "Bottom"] <- "bottom"
room_2$subzone[room_2$subzone == "Middle"] <- "middle"
room_2$subzone[room_2$subzone == "Top"] <- "top"


print("what makes up subzone col")
unique(room_2$subzone)

print("how many NAs in DateTime and Subzone")
sum(is.na(room_2$DateTime))
sum(is.na(room_2$subzone))

#room_2$accessdate <- dmy_hms(room_2$accessdate)
# This is a hack to work with the downloaded data from excel and onedrive
room_2$accessdate <- ymd_hms(room_2$DateTime)

# find the five number summary to determine the median interval in seconds of each reading to determine the proper sampling interval
# mean of the median times for room 2 is 9 minutes so move up to 10 minutes
# mean of the mean times for room 2 is 38 minutes so move down to every 30 minutes
room_2_summary <- room_2 |> nest(data = - tagname) |> 
 na.exclude() |>
 mutate(id_dupes = map(data ,~identify_duplicate_records(.x))) |>
 mutate(cleaned = map(id_dupes, ~.x[! .x$duplicate == 1,])) |>
 mutate(tsibble = map(cleaned, ~tsibble(datetime = ymd_hms(.x$accessdate), value = .x$subzone, index = datetime) )) |>
 mutate(intervals_s = map(tsibble, ~ as.numeric(difftime(.x$datetime[1:(length(.x$datetime)-1)], .x$datetime[2:length(.x$datetime)],units='secs') ))) |>
 mutate(summary = map(intervals_s, ~summary(.x))) |>
 mutate(minimum = map(summary, ~abs(.x[6]))) |>
 mutate(median = map(summary, ~.x[3])) |>
 mutate(mean = map(summary, ~.x[4])) |>
 mutate(first_rec =map(tsibble, ~head(.x$datetime, n=1))) |>
 mutate(last_rec = map(tsibble, ~tail(.x$datetime, n=1))) |> 
 unnest(c(first_rec, last_rec, minimum, median,mean))

# Time in minutes and min in sec of average duration between transitions
(mean(room_2_summary$median)/60)
(mean(room_2_summary$mean)/60)
(min(room_2_summary$minimum))

# when is a nice time to start the study?

# No Room 3 2021-02-18 T23:30:00/2021-05-06 T23:00:00
# All Rooms 2021-03-09 T20:00:00/2021-05-06 T23:00:00

# 
room_2_struct <- room_2 |> nest(data = - tagname) |> 
 na.exclude() |>
 mutate(id_dupes = map(data ,~identify_duplicate_records(.x))) |>
 mutate(cleaned = map(id_dupes, ~.x[! .x$duplicate == 1,])) |>
 mutate(tsibble = map(cleaned, ~tsibble(datetime = ymd_hms(.x$accessdate), value = .x$subzone, index = datetime) )) 
```

# All Room Time Budget Analysis

```{r all room analysis}

# No Room 3 2021-02-18 T23:30:00/2021-05-06 T23:00:00

room_2_all_analysis <- room_2_struct |>
 mutate(slicedTsibble = map(tsibble, ~ sliceTsibble(.x, "2021-02-18 T23:30:00", "2021-05-06 T23:00:00")))

(room_2_boundries <- data.frame(room_2_summary$tagname, room_2_summary$first_rec, room_2_summary$last_rec))


room_2_all_analysis <- room_2_all_analysis |>
 filter(!is.na(slicedTsibble)) |> 
 filter(!(tagname %in% c("6910","6966","6914")))
  
# interpolate the rest of the intervals
room_2_regular <- room_2_all_analysis |>
 select(c(tagname, slicedTsibble)) |>
 mutate(near_5 = map(slicedTsibble, ~ nice_start(.x, "5 seconds",5/60))) |>
 mutate(perSec = map(near_5, ~ fill_gaps(.x)))|>
 mutate(sampled = map(perSec, ~ na.locf(.x))) 

room_2_dupes <- room_2_regular |>
  select(tagname, sampled) |> 
  mutate(duplicates = map(sampled, ~duplicates(.x)))

room_2_interval <- room_2_regular |>
  mutate(interval = map(sampled, ~timeToIntervals(.x))) 

# TODO need to set start and end timepoints for this dataset.
room_2_all_room_time_budget <- room_2_interval |>
  mutate(tb = map(interval, ~ getTimeBudgetProp(.x))) |>
  unnest(tb) 

room_2_all_room_time_budget |>
 select(c(tagname, Interval.1., Interval.2., X1, X2, X3)) |> 
 write.csv(row.names=F, '../output/all_rooms/room_2_all_room_time_budget.csv')

room_2_interval |> 
 unnest(interval) |>
 select(c(tagname, t1,t2,to_zone)) |> 
 write.csv(row.names=F,'../output/all_rooms/room_2_all_room_interval_tab.csv')


for(i in 1:length(room_2_struct$tagname)){

    current_tag <- room_2_struct$tagname[i]

    current_tsibble <- room_2_struct |>
        slice(i) |> 
        pull(tsibble) |> 
        pluck(1)

    current_tsibble$tagname <- rep(current_tag, length(current_tsibble$datetime))

    write.csv(current_tsibble, paste0("../intermediate/all_rooms/room_2_tsibble_",current_tag,".csv"),row.names=F)
}

 ```

 ### All Room Daily Time Budget Analysis

 ```{r all room daily time budget}

# Make day and night "raw data" tables

room_2_all_room_day <- room_2_interval |>
  mutate(day = map(sampled, ~ getDayRecords(.x,"05:00","22:00"))) |>
  mutate(night = map(sampled, ~ getNightRecords(.x,"05:00","22:00"))) 

# Turn day and night tables into daily interval tables

room_2_all_room_day <- room_2_all_room_day |>
  mutate(day_int = map(day, ~ nestedTimeToIntervals(.x))) |>
  mutate(night_int = map(night, ~ nestedTimeToIntervals(.x)))


# Run getTimeBudgetProp for each daily interval tables

 room_2_all_room_time_budget <- room_2_all_room_day |>
  mutate(daily_tb = map(day_int, ~ map(.x$daily_int, ~ getTimeBudgetPropDayNight(.x)))) |>
  mutate(night_tb = map(night_int, ~ map(.x$daily_int, ~ getTimeBudgetPropDayNight(.x))))


for(i in 1:length(room_2_all_room_time_budget$tagname)){

    current_tag <- room_2_all_room_time_budget$tagname[i]

    current_day_tb<- room_2_all_room_time_budget |>
        slice(i) |> 
        pull(daily_tb) |> 
        pluck(1)

    current_day_tb_df <- do.call(rbind, current_day_tb)
    columns = c("interval1","interval2","Bottom","Middle","Top")

    colnames(current_day_tb_df) <- columns

    current_day_tb_df$tagname <- rep(current_tag, length(current_day_tb_df$interval1))

    write.csv(current_day_tb_df, paste0("../intermediate/all_rooms/room_2_day_time_budget_",current_tag,".csv"),row.names=F)

    current_night_tb <- room_2_all_room_time_budget |>
        slice(i) |> 
        pull(night_tb) |> 
        pluck(1)

    current_night_tb_df <- do.call(rbind, current_night_tb)
    columns = c("interval1","interval2","Bottom","Middle","Top")

    colnames(current_night_tb_df) <- columns

    current_night_tb_df$tagname <- rep(current_tag, length(current_night_tb_df$interval1))

    write.csv(current_night_tb_df, paste0("../intermediate/all_rooms/room_2_night_time_budget_",current_tag,".csv"),row.names=F)
}

```


```{r read in the generated time budgets}
library(readr)
library(ggplot2)

day_tbs <- Sys.glob("../intermediate/all_rooms/room_2_day_time_budget_*")

night_tbs <- Sys.glob("../intermediate/all_rooms/room_2_night_time_budget_*")

day_tbs_df <- read_csv(day_tbs)

nest_day_tbs <- day_tbs_df |>
  nest(data = -tagname)

night_tbs_df <- read_csv(night_tbs)

nest_night_tbs <- night_tbs_df |>
   nest(data = - tagname)

#plot id #3

for(i in 1:length(nest_day_tbs$tagname)){

sb_data <- cbind(nest_day_tbs$data[[i]][1:2], stack(nest_day_tbs$data[[i]][3:5]))

sb_data$ind <- factor(sb_data$ind, levels=c("Top","Middle","Bottom"))

datebreaks <- seq(as.Date(ymd_hms(head(unique(sb_data$interval1),n=1))), as.Date(ymd_hms(tail(unique(sb_data$interval1),n=1))), by="7 days")

datebreaks <- c(datebreaks, as.Date(ymd_hms(tail(unique(sb_data$interval1),n=1))))

all_datebreak <- seq(as.Date(ymd_hms(head(unique(sb_data$interval1),n=1))), as.Date(ymd_hms(tail(unique(sb_data$interval1),n=1))), by="1 days")

day_3_plot <- ggplot(data= sb_data, aes(x = as.Date(interval1), y= values, group=ind, color=ind)) +
  geom_point() + 
  theme_bw() + 
  scale_x_date(breaks= datebreaks, minor_breaks=all_datebreak) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  xlab("Day of Study") + 
  ylab("Prop. of Time Spent in Zone") +
  ggtitle(paste0("Daily Time Budget for Each Day for Bird ID: ", nest_day_tbs[i,1])) + 
  scale_colour_discrete( name ="Zone") +
  scale_y_continuous(limits=c(0, 1.001))

ggsave(paste0("../figures/all_day/day_daily_time_budget_point_for_", nest_day_tbs[i,1],".png"), day_3_plot)

day_3_plot_line <- ggplot(data= sb_data, aes(x = as.Date(interval1), y= values, group=ind, color=ind)) +
  geom_line() + 
  theme_bw() + 
  scale_x_date(breaks= datebreaks, minor_breaks=all_datebreak) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  xlab("Day of Study") + 
  ylab("Prop. of Time Spent in Zone") +
  ggtitle(paste0("Daily Time Budget for Each Day for Bird ID: ", nest_day_tbs[i,1])) + 
  scale_colour_discrete( name ="Zone") +
  scale_y_continuous(limits=c(0, 1.001))

ggsave(paste0("../figures/all_day/day_daily_time_budget_line_for_", nest_day_tbs[i,1],".png"), day_3_plot_line)

day_3_sb_plot <- ggplot(data = sb_data, aes(x = as.Date(interval1), y=values, fill=ind)) + 
geom_bar(stat="identity") +
theme_bw() +  
xlab("Day of Study") + 
ylab("Prop. of Time Spent in Zone") +
scale_x_date(breaks= datebreaks, minor_breaks=all_datebreak) + 
theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
ggtitle(paste0("Daily Time Budget for Each Day for Bird ID: ", nest_day_tbs[i,1])) + 
labs(fill = "Zone") + 
scale_y_continuous(limits=c(0, 1.001))

ggsave(paste0("../figures/all_day/day_daily_time_budget_stack_bar_for_", nest_day_tbs[i,1],".png"), day_3_sb_plot)
}


for(i in 1:length(nest_night_tbs$tagname)){

sb_data <- cbind(nest_night_tbs$data[[i]][1:2], stack(nest_night_tbs$data[[i]][3:5]))

sb_data$ind <- factor(sb_data$ind, levels=c("Top","Middle","Bottom"))

datebreaks <- seq(as.Date(ymd_hms(head(unique(sb_data$interval1),n=1))), as.Date(ymd_hms(tail(unique(sb_data$interval1),n=1))), by="7 days")

datebreaks <- c(datebreaks, as.Date(ymd_hms(tail(unique(sb_data$interval1),n=1))))

all_datebreak <- seq(as.Date(ymd_hms(head(unique(sb_data$interval1),n=1))), as.Date(ymd_hms(tail(unique(sb_data$interval1),n=1))), by="1 days")

day_3_plot <- ggplot(data= sb_data, aes(x = as.Date(interval1), y= values, group=ind, color=ind)) +
  geom_point() + 
  theme_bw() + 
  scale_x_date(breaks= datebreaks, minor_breaks=all_datebreak) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  xlab("Day of Study") + 
  ylab("Prop. of Time Spent in Zone") +
  ggtitle(paste0("Daily Time Budget for Each Night for Bird ID: ", nest_day_tbs[i,1])) + 
  scale_colour_discrete( name ="Zone") +
  scale_y_continuous(limits=c(0, 1.001))

ggsave(paste0("../figures/all_day/night_daily_time_budget_point_for_", nest_day_tbs[i,1],".png"), day_3_plot)

day_3_plot_line <- ggplot(data= sb_data, aes(x = as.Date(interval1), y= values, group=ind, color=ind)) +
  geom_line() + 
  theme_bw() + 
  scale_x_date(breaks= datebreaks, minor_breaks=all_datebreak) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  xlab("Day of Study") + 
  ylab("Prop. of Time Spent in Zone") +
  ggtitle(paste0("Daily Time Budget for Each Night for Bird ID: ", nest_day_tbs[i,1])) + 
  scale_colour_discrete( name ="Zone") +
  scale_y_continuous(limits=c(0, 1.001))

ggsave(paste0("../figures/all_day/night_daily_time_budget_line_for_", nest_day_tbs[i,1],".png"), day_3_plot_line)

day_3_sb_plot <- ggplot(data = sb_data, aes(x = as.Date(interval1), y=values, fill=ind)) + 
geom_bar(stat="identity") +
theme_bw() +  
xlab("Day of Study") + 
ylab("Prop. of Time Spent in Zone") +
scale_x_date(breaks= datebreaks, minor_breaks=all_datebreak) + 
theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
ggtitle(paste0("Daily Time Budget for Each Night for Bird ID: ", nest_day_tbs[i,1])) + 
labs(fill = "Zone") + 
scale_y_continuous(limits=c(0, 1.001))

ggsave(paste0("../figures/all_day/night_daily_time_budget_stack_bar_for_", nest_day_tbs[i,1],".png"), day_3_sb_plot)
}

for(i in 1:length(nest_night_tbs$tagname)){

df_2 <- aggregate(sb_data$values, list(as.Date(sb_data$interval1), sb_data$ind), FUN=sum)

date_to_day <- data.frame(as.Date(unique(df_2$Group.1)), c(1:length(unique(df_2$Group.1))))
colnames(date_to_day) <- c('datetime','dos')

df_2$dos <- match(df_2$Group.1, date_to_day$datetime)

df_2$ind <- factor(df_2$Group.2, levels=c("Top","Middle","Bottom"))

#datebreaks <- seq(as.Date(head(unique(df_2$Group.1),n=1)), as.Date(tail(unique(df_2$Group.1),n=1)), by="7 days")

#datebreaks <- c(datebreaks, as.Date(tail(unique(df_2$Group.1),n=1)))

#all_datebreak <- seq(as.Date(head(unique(df_2$Group.1),n=1)), as.Date(tail(unique(df_2$Group.1),n=1)), by="1 days")

day_3_plot <- ggplot(data= df_2, aes(x = dos, y= x, group=ind, color=ind)) +
  geom_point() + 
  theme_bw() + 
  #scale_x_date(breaks= datebreaks, minor_breaks=all_datebreak) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  xlab("Day of Study") + 
  ylab("Prop. of Time Spent in Zone") +
  ggtitle(paste0("Daily Time Budget for Each Night for Bird ID: ", nest_day_tbs[i,1])) + 
  scale_colour_discrete( name ="Zone") +
  scale_y_continuous(limits=c(0, 1))

ggsave(paste0("../figures/all_day/night_daily_time_budget_point_for_", nest_day_tbs[i,1],".png"), day_3_plot)

day_3_plot_line <- ggplot(data= df_2, aes(x = dos, y= x, group=ind, color=ind)) +
  geom_line() + 
  theme_bw() + 
  #scale_x_date(breaks= datebreaks, minor_breaks=all_datebreak) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  xlab("Day of Study") + 
  ylab("Prop. of Time Spent in Zone") +
  ggtitle(paste0("Daily Time Budget for Each Night for Bird ID: ", nest_day_tbs[i,1])) + 
  scale_colour_discrete( name ="Zone") +
  scale_y_continuous(limits=c(0, 1))

ggsave(paste0("../figures/all_day/night_daily_time_budget_line_for_", nest_day_tbs[i,1],".png"), day_3_plot_line)

day_3_sb_plot <- ggplot(data = df_2, aes(x = dos, y=x, fill=ind)) + 
geom_bar(stat="identity") +
theme_bw() +  
xlab("Day of Study") + 
ylab("Prop. of Time Spent in Zone") +
#scale_x_date(breaks= datebreaks, minor_breaks=all_datebreak) + 
theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
ggtitle(paste0("Daily Time Budget for Each Night for Bird ID: ", nest_day_tbs[i,1])) + 
labs(fill = "Zone") + 
ylim(0,1.001)
scale_y_continuous(limits=c(-0.1, 1.1), labels=c(0,.25,.5,.75,1) )

ggsave(paste0("../figures/all_day/night_daily_time_budget_stack_bar_for_", nest_day_tbs[i,1],".png"), day_3_sb_plot)
}
```


```{r}

day_tbs_df 
day_flat <- cbind(day_tbs_df[c(1:2,6)], stack(day_tbs_df[3:5]))

day_flat$ind <- factor(day_flat$ind, levels=c("Top","Middle","Bottom"))

datebreaks <- seq(as.Date(ymd_hms(head(unique(day_flat$interval1),n=1))), as.Date(ymd_hms(tail(unique(day_flat$interval1),n=1))), by="7 days")

datebreaks <- c(datebreaks, as.Date(ymd_hms(tail(unique(day_flat$interval1),n=1))))

all_datebreak <- seq(as.Date(ymd_hms(head(unique(day_flat$interval1),n=1))), as.Date(ymd_hms(tail(unique(day_flat$interval1),n=1))), by="1 days")

room_2_sb_plot <- ggplot(data = day_flat, aes(x = as.Date(interval1), y=values, fill=ind)) + 
geom_bar(stat="identity") +
theme_bw() +  
xlab("Day of Study") + 
ylab("Prop. of Time Spent in Zone") +
scale_x_date(breaks= datebreaks, minor_breaks=all_datebreak) + 
theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
ggtitle("Daily Time Budget for Each Night for Room 2") + 
labs(fill = "Zone") +
scale_y_continuous(limits=c(0, 11.001))

ggsave(paste0("../figures/all_day/day_daily_time_budget_stack_bar_for_room_2",".png"), room_2_sb_plot)


room_2_bp <- ggplot(day_flat, aes(x = factor(as.Date(interval1)), y=values, fill=ind)) + 
  geom_boxplot()

ggsave(paste0("../figures/all_day/day_daily_time_budget_boxplot_for_room_2",".png"), room_2_bp)


night_tbs_df 

```

 # No Room 3 Time Budget Analysis

```{r no room 3 analysis}
gc()
# All Rooms 2021-03-09 T20:00:00/2021-05-06 T23:00:00

room_2_no_3 <- room_2_struct |>
 mutate(slicedTsibble = map(tsibble, ~ sliceTsibble(.x, "2021-03-09 20:00:00", "2021-05-06 23:00:00")))

(room_2_boundries <- data.frame(room_2_summary$tagname, room_2_summary$first_rec, room_2_summary$last_rec))


room_2_no_3 <- room_2_no_3 |>
 filter(!is.na(slicedTsibble)) |> 
 filter(!(tagname %in% c("6910","6966","6914")))
  
# # Previous Method that is too memory Intesive
# interpolate the rest of the intervals
# room_2_no_3_regular <- room_2_no_3 |>
#  select(c(tagname, slicedTsibble)) |>
#  mutate(near_5 = map(slicedTsibble, ~ nice_start(.x, "5 seconds",5/60))) |>
#  mutate(perSec = map(near_5, ~ fill_gaps(.x)))|>
#  mutate(sampled = map(perSec, ~ na.locf(.x))) 

# room_2_no_3_interval <- room_2_no_3_regular |>
#   mutate(interval = map(sampled, ~timeToIntervals(.x))) 

# room_2_no_3_time_budget <- room_2_no_3_interval |>
#   mutate(tb = map(interval, ~ getTimeBudgetProp(.x))) |>
#   unnest(tb) 

room_2_no_3_time_budget <- room_2_no_3 |>
 select(c(tagname, slicedTsibble)) |>
 mutate(near_5 = map(slicedTsibble, ~ nice_start(.x, "5 seconds",5/60))) |> 
 mutate(interval = map(near_5, ~timeToIntervals(.x))) |>
 mutate(tb = map(interval, ~ getTimeBudgetProp(.x))) |>
 unnest(tb)

room_2_dupes <- room_2_no_3_time_budget |>
  select(tagname, near_5) |> 
  mutate(duplicates = map(near_5, ~duplicates(.x)))


room_2_no_3_time_budget |>
 select(c(tagname, Interval.1., Interval.2., X1, X2, X3)) |> 
 write.csv(row.names=F, '../output/no_room_3/room_2_no_room_3_time_budget.csv')

room_2_no_3_time_budget |> 
 unnest(interval) |>
 select(c(tagname, t1,t2,zone)) |> 
 write.csv(row.names=F,'../output/no_room_3/room_2_no_room_3_interval_tab.csv')

 ```

```{r check assumptions about two processes, eval=FALSE}

room_2_no_3_time_budget$tagname == room_2_no_3_time_budget_skip_second$tagname

room_2_no_3_time_budget$Interval.1. == room_2_no_3_time_budget_skip_second$Interval.1.

room_2_no_3_time_budget$Interval.2. == room_2_no_3_time_budget_skip_second$Interval.2.

room_2_no_3_time_budget$X1 == room_2_no_3_time_budget_skip_second$X1
room_2_no_3_time_budget$X2 == room_2_no_3_time_budget_skip_second$X2
room_2_no_3_time_budget$X3 == room_2_no_3_time_budget_skip_second$X3

```

```{r test the time to intervals function }
library(testthat)

zero_case <- timeToIntervals(room_2_all_room_day$day_int[[1]]$by_day[[27]][1:10,])

one_case <- timeToIntervals(room_2_all_room_day$day_int[[2]]$by_day[[14]])

two_data <- bind_rows(room_2_all_room_day$day_int[[9]]$by_day[[31]][2705:2709,], room_2_all_room_day$day_int[[9]]$by_day[[31]][2725:2726,])
two_case <- timeToIntervals(two_data)

three_data <- bind_rows(room_2_all_room_day$day_int[[9]]$by_day[[31]][2705:2709,], room_2_all_room_day$day_int[[9]]$by_day[[31]][2725:2726,],room_2_all_room_day$day_int[[9]]$by_day[[31]][4400:4444,])
three_case <- timeToIntervals(three_data)

four_data <- bind_rows(room_2_all_room_day$day_int[[9]]$by_day[[31]][2705:2709,], room_2_all_room_day$day_int[[9]]$by_day[[31]][2725:2726,],room_2_all_room_day$day_int[[9]]$by_day[[31]][4400:4444,],room_2_all_room_day$day_int[[9]]$by_day[[31]][7960:7966,])

four_case <- timeToIntervals(four_data)

zero_trans_res <- expect_equal(dim(timeToIntervals(room_2_all_room_day$day_int[[1]]$by_day[[27]][100:200,])),dim(zero_case),label="case 0 trans")

one_trans_res <- expect_equal(dim(timeToIntervals(room_2_all_room_day$day_int[[14]]$by_day[[10]])), dim(one_case), label="case 1 trans")

two_trans_res <- expect_equal(dim(timeToIntervals(room_2_all_room_day$day_int[[1]]$by_day[[2]])), dim(two_case), label="case 2 trans")

three_trans_res <- expect_equal(dim(timeToIntervals(room_2_all_room_day$day_int[[3]]$by_day[[13]])), dim(three_case), label="case 3 trans")

four_trans_res <- expect_equal(dim(timeToIntervals(room_2_all_room_day$day_int[[19]]$by_day[[12]])), dim(four_case), label="case 4 trans")

```

```{r test the time budget function }
library(testthat)

zero_case <- timeToIntervals(room_2_all_room_day$day_int[[1]]$by_day[[27]][1:10,])

one_case <- timeToIntervals(room_2_all_room_day$day_int[[2]]$by_day[[14]])

two_data <- bind_rows(room_2_all_room_day$day_int[[9]]$by_day[[31]][2705:2709,], room_2_all_room_day$day_int[[9]]$by_day[[31]][2725:2726,])
two_case <- timeToIntervals(two_data)

three_data <- bind_rows(room_2_all_room_day$day_int[[9]]$by_day[[31]][2705:2709,], room_2_all_room_day$day_int[[9]]$by_day[[31]][2725:2726,],room_2_all_room_day$day_int[[9]]$by_day[[31]][4400:4444,])
three_case <- timeToIntervals(three_data)

four_data <- bind_rows(room_2_all_room_day$day_int[[9]]$by_day[[31]][2705:2709,], room_2_all_room_day$day_int[[9]]$by_day[[31]][2725:2726,],room_2_all_room_day$day_int[[9]]$by_day[[31]][4400:4444,],room_2_all_room_day$day_int[[9]]$by_day[[31]][7960:7966,])

four_case <- timeToIntervals(four_data)

zero_trans_res <- expect_equal(dim(timeToIntervals(room_2_all_room_day$day_int[[1]]$by_day[[27]][100:200,])),dim(zero_case),label="case 0 trans")

one_trans_res <- expect_equal(dim(timeToIntervals(room_2_all_room_day$day_int[[14]]$by_day[[10]])), dim(one_case), label="case 1 trans")

two_trans_res <- expect_equal(dim(timeToIntervals(room_2_all_room_day$day_int[[1]]$by_day[[2]])), dim(two_case), label="case 2 trans")

three_trans_res <- expect_equal(dim(timeToIntervals(room_2_all_room_day$day_int[[3]]$by_day[[13]])), dim(three_case), label="case 3 trans")

four_trans_res <- expect_equal(dim(timeToIntervals(room_2_all_room_day$day_int[[19]]$by_day[[12]])), dim(four_case), label="case 4 trans")


night_data_issue <- room_2_all_room_day$night_int[[1]]$by_day[[77]]

data <- room_2_interval$sampled[[5]]

data <- room_2_all_room_day$night[[10]]

data <- room_2_all_room_day$night_int[[1]]$by_day[[69]]

data <- room_2_all_room_day$night_int[[1]]$by_day[[85]]

```


breaks= datebreaks, minor_
breaks= datebreaks, minor_