---
title: "RFID Room 2"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---


# Data Preprocessing

```{r function to clean data from duplicate reads}
identify_duplicate_records <- function(records){
  records$duplicate <- rep(0, length(records$subzone))
  records <- records[order(records$accessdate),]
  
  for(i in 3:length(records$subzone)){

    primary <- records[i-2,]
    secondary <- records[i-1,]
    tertiary <- records[i,]
    #print(primary)

    #print(paste(primary$subzone," : ",secondary$subzone))
  
  
    #check if primary zone is same as secondary zone
    if(length(unique(c(primary$subzone,secondary$subzone,tertiary$subzone)))!=3){
      if(primary$subzone != secondary$subzone){
        records[[i-2,"duplicate"]] <- 1
      } else if(secondary$subzone != tertiary$subzone){
        records[[i-1,"duplicate"]] <- 1
      }
    }

  }
  return(records)
}

```

```{r from Kenis data}
# from Analyis.R generated by Keni
# calculates the proportion of time spent in each zone based on the whole time series passed in
 getTimeBudgetProp <- function(data) {
  columns = c("interval","Bottom","Middle","Top") 
  TBS = data.frame(matrix(nrow = 0, ncol = length(columns))) 
  colnames(TBS) = columns

  # store inteval as minutes
  TBStag<- data.frame(t = (as.numeric(data$t2) - as.numeric(data$t1)) / 60, zone=data$zone)

  Interval <- c(ymd_hms(as.POSIXct.numeric(as.numeric(head(data,n=1)$t1),origin=origin)),ymd_hms(as.POSIXct.numeric(as.numeric(tail(data,n=1)$t2),origin=origin)))

  TBbot<-sum(TBStag[which(TBStag$zone == "bottom"),]$t)/sum(TBStag$t)
    
  TBmid<-sum(TBStag[which(TBStag$zone == "middle"),]$t)/sum(TBStag$t)
     
  TBtop<-sum(TBStag[which(TBStag$zone == "top"),]$t)/sum(TBStag$t)
     
  TBS<-matrix(c(TBbot,TBmid,TBtop),ncol=3)
     
  return(data.frame(Interval[1],Interval[2],TBS))
  
}

getTimeBudgetAbs <- function(data) {
  columns = c("Bottom","Middle","Top") 
  TBS = data.frame(matrix(nrow = 0, ncol = length(columns))) 
  colnames(TBS) = columns

  # store inteval as minutes
  TBStag<- data.frame(t = (as.numeric(data$t2) - as.numeric(data$t1)) / 60, zone=data$zone)

  TBbot<-sum(TBStag[which(TBStag$zone == "bottom"),]$t)
    
  TBmid<-sum(TBStag[which(TBStag$zone == "middle"),]$t)
     
  TBtop<-sum(TBStag[which(TBStag$zone == "top"),]$t)

  TBS<-matrix(c(TBbot,TBmid,TBtop),ncol=3)
     
  return(TBS)
  
}

timeToIntervals <- function(data){
  requireNamespace("dplyr")

  interval_table <- data.frame()

  first_entry <- head(data,n=1)
  transition_into <- data[which(data$value != dplyr::lag(data$value)),]
  last_entry <- tail(data,n=1)


  new_row <- cbind(ymd_hms(first_entry$datetime),ymd_hms(transition_into[1,]$datetime),as.character(first_entry$value))
  interval_table <- rbind(interval_table, new_row)

  for(i in 2:length(transition_into$value)-1){
    new_row <- cbind(ymd_hms(transition_into[i,]$datetime), ymd_hms(transition_into[i+1,]$datetime),as.character(transition_into[i,2]))
    interval_table <- rbind(interval_table, new_row)
  }
  colnames(interval_table) <- c("t1","t2","zone")
  interval_table[length(interval_table$t2),]$t2 <- last_entry$datetime

  return(interval_table)

}

sliceTsibble <- function(data, start, stop){
  
  previous_state <- tail(data[data$datetime <= ymd_hms(start),],n=1)
  greater_than_start <- data[data$datetime >= ymd_hms(start),]
  less_than_end <- greater_than_start[greater_than_start$datetime <= ymd_hms(stop),]
  final_state <- head(greater_than_start[greater_than_start$datetime >= ymd_hms(stop),],n=1)


  if(nrow(less_than_end) == 0){
    less_than_end <- NA
    return(less_than_end)
  }

  previous_state$datetime <- ymd_hms(start)
  final_state$datetime <- ymd_hms(stop)
  less_than_end <- bind_rows(less_than_end, previous_state)
  less_than_end <- bind_rows(less_than_end, final_state)
  return(less_than_end)
  
}
```

```{r nice start function}

nice_start <- function(dataframe, units, interval_min){
  requireNamespace("lubridate")
  dataframe[1,1]$datetime <- round_date(ymd_hms(dataframe[1,1]$datetime), unit=units)
  attr(dataframe, 'interval') <- new_interval(min=interval_min)
  # remove duplicate entries 
  #dataframe <- dataframe[!duplicates(dataframe)]

  return(dataframe)
}

```

## Import Room 3

```{r generate transition tables for room 2}

library(xts)
library(lubridate)
library(tidyverse)
library(tidyr)
library(dplyr)
library(tsibble)


room_11 <- read.csv("../data/DK20-03-RFID-R11-febmay-080423.csv") %>% na.exclude()

bird_ids_room_11 <- unique(room_11$tagname)
bird_ids_room_11 <- na.trim(sort(bird_ids_room_11))

room_11["DateTime"] <- as.POSIXct(room_11$access, origin="1970-01-01", tz="GMT")

print("what makes up subzone col")
unique(room_11$subzone)

room_11$subzone[room_11$subzone == "Bottom"] <- "bottom"
room_11$subzone[room_11$subzone == "Middle"] <- "middle"
room_11$subzone[room_11$subzone == "Top"] <- "top"


print("what makes up subzone col")
unique(room_11$subzone)

print("how many NAs in DateTime and Subzone")
sum(is.na(room_11$DateTime))
sum(is.na(room_11$subzone))

room_11$accessdate <- dmy_hms(room_11$accessdate)

# find the five number summary to determine the median interval in seconds of each reading to determine the proper sampling interval
# mean of the median times for room 2 is 9 minutes so move up to 10 minutes
# mean of the mean times for room 2 is 38 minutes so move down to every 30 minutes
room_11_summary <- room_11 |> nest(data = - tagname) |> 
 na.exclude() |>
 mutate(id_dupes = map(data ,~identify_duplicate_records(.x))) |>
 mutate(cleaned = map(id_dupes, ~.x[! .x$duplicate == 1,])) |>
 mutate(tsibble = map(cleaned, ~tsibble(datetime = ymd_hms(.x$accessdate), value = .x$subzone, index = datetime) )) |>
 mutate(intervals_s = map(tsibble, ~ as.numeric(difftime(.x$datetime[1:(length(.x$datetime)-1)], .x$datetime[2:length(.x$datetime)],units='secs') ))) |>
 mutate(summary = map(intervals_s, ~summary(.x))) |>
 mutate(minimum = map(summary, ~abs(.x[6]))) |>
 mutate(median = map(summary, ~.x[3])) |>
 mutate(mean = map(summary, ~.x[4])) |>
 mutate(first_rec =map(tsibble, ~head(.x$datetime, n=1))) |>
 mutate(last_rec = map(tsibble, ~tail(.x$datetime, n=1))) |> 
 unnest(c(first_rec, last_rec, minimum, median,mean))

# Time in minutes and min in sec of average duration between transitions
(mean(room_11_summary$median)/60)
(mean(room_11_summary$mean)/60)
(min(room_11_summary$minimum))

# when is a nice time to start the study?

# No Room 3 2021-02-18 T23:30:00/2021-05-06 T23:00:00
# All Rooms 2021-03-09 T20:00:00/2021-05-06 T23:00:00

# 
room_11_struct <- room_11 |> nest(data = - tagname) |> 
 na.exclude() |>
 mutate(id_dupes = map(data ,~identify_duplicate_records(.x))) |>
 mutate(cleaned = map(id_dupes, ~.x[! .x$duplicate == 1,])) |>
 mutate(tsibble = map(cleaned, ~tsibble(datetime = ymd_hms(.x$accessdate), value = .x$subzone, index = datetime) )) 
```

# All Room Time Budget Analysis

```{r all room analysis}

# All Rooms 2021-03-09 T20:00:00/2021-05-06 T23:00:00

room_11_all_analysis <- room_11_struct |>
 mutate(slicedTsibble = map(tsibble, ~ sliceTsibble(.x, "2021-03-09 20:00:00", "2021-05-06 23:00:00")))

(room_11_boundries <- data.frame(room_11_summary$tagname, room_11_summary$first_rec, room_11_summary$last_rec))


room_11_all_analysis <- room_11_all_analysis |>
 filter(!is.na(slicedTsibble)) |> 
 filter(!(tagname %in% c("6888")))
  
# round the first entry to the nearest 5 second interval to provide a nice sampling interval, then interpolate the rest of the intervals
room_11_regular <- room_11_all_analysis |>
 select(c(tagname, slicedTsibble)) |>
 mutate(near_5 = map(slicedTsibble, ~ nice_start(.x, "5 seconds",5/60))) |>
 mutate(perSec = map(near_5, ~ fill_gaps(.x)))|>
 mutate(sampled = map(perSec, ~ na.locf(.x))) 

room_11_dupes <- room_11_regular |>
  select(tagname, sampled) |> 
  mutate(duplicates = map(sampled, ~duplicates(.x)))

room_11_interval <- room_11_regular |>
  mutate(interval = map(sampled, ~timeToIntervals(.x))) 

# TODO need to set start and end timepoints for this dataset.
room_11_all_room_time_budget <- room_11_interval |>
  mutate(tb = map(interval, ~ getTimeBudgetProp(.x))) |>
  unnest(tb)

room_11_all_room_time_budget |>
 select(c(tagname, Interval.1., Interval.2., X1, X2, X3)) |> 
 write.csv(row.names=F, '../output/room_11_all_room_time_budget.csv')

room_11_interval |> 
 unnest(interval) |>
 select(c(tagname, t1,t2,zone)) |> 
 write.csv(row.names=F, '../output/room_11_all_room_interval_tab.csv')


for(i in 1:length(room_11_struct$tagname)){

    current_tag <- room_11_struct$tagname[i]

    current_tsibble <- room_11_struct |>
        slice(i) |> 
        pull(tsibble) |> 
        pluck(1)

    current_tsibble$tagname <- rep(current_tag, length(current_tsibble$datetime))

    write.csv(current_tsibble, paste0("../intermediate/room_11_tsibble_",current_tag,".csv"),row.names=F)
}

 ```