---
title: "RFID Room 2"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---


# Data Preprocessing
## Function to find the most frequent zone (average wont quite work)

```{r find most frequent zone}
MaxTable <- function(x){
     dd <- unique(x)
     dd[which.max(tabulate(match(x,dd)))]
}

```

## My to minute function

```{r my to minute}
to_minute <- function(xts_object){
  ep_min <- endpoints(na.omit(xts_object), on="minutes",k=60)
  ave_min <- period.apply(na.omit(xts_object), INDEX=ep_min, FUN=MaxTable)
  #this removes the time to allow cbinding
  ave_min <- to.minutes(ave_min,OHLC=F,indexAt="startof")
  return(ave_min)
}
```

## My to daily function

```{r my to daily}
 to_daily <- function(xts_object){
   ep_day <- endpoints(na.omit(xts_object), on="minutes",k=1440)
   ave_day <- period.apply(na.omit(xts_object), INDEX=ep_day, FUN=MaxTable)
   #this removes the time to allow cbinding
   ave_day <- to.daily(ave_day,OHLC=F,indexAt="startof")
   return(ave_day)
 }
```

## My to weekly function

```{r my to weekly}
to_weekly <- function(xts_object){
  ep_week <- endpoints(na.omit(xts_object), on="minutes",k=10080)
  ave_week <- period.apply(na.omit(xts_object), INDEX=ep_week, FUN=MaxTable)
  #this removes the time to allow cbinding
  ave_week <- to.weekly(ave_week,OHLC=F,indexAt="startof")
  return(ave_week)
}
```

## My to monthly function

```{r my to monthly}
to_monthly <- function(xts_object){
  ep_month <- endpoints(na.omit(xts_object), on="minutes",k=43800)
  ave_month <- period.apply(na.omit(xts_object), INDEX=ep_month, FUN=MaxTable)
  #this removes the time to allow cbinding
  ave_month <- to.monthly(ave_month,OHLC=F,indexAt="startof")
  return(ave_month)
}
```


## Function to Calculate Transitions

```{r function to calc transitions}
#I don't know when we use this data yet, will be useful when making transition tables for the whole dataset 
sep_bird_id_xts <- function(samp_name, samp_id,cage_obj){
  
  raw_sample_tab <- subset(cage_obj, tagname==samp_id)
  
  xts_object <- xts(raw_sample_tab ,order.by = raw_sample_tab$DateTime)
  
  result <- list("name" = samp_name, "ID"=samp_id, "xts_obj"=xts_object)
  return(result)
}

sep_bird_id_period <- function(samp_name, samp_id, cage_obj, cutoff){
  
  raw_sample_tab <- subset(cage_obj, tagname==samp_id)
  
  xts_object <- xts(raw_sample_tab ,order.by=raw_sample_tab$DateTime)
  
  xts_object <- xts_object[cutoff]
  
  daily <- to_daily(xts_object$subzone)#, OHLC=F)
  weekly <- to_weekly(xts_object$subzone)#, OHLC=F)
  monthly <- to_monthly(xts_object$subzone)#, OHLC=F)
  index(monthly) <-as.POSIXct(index(monthly))
  
  result <- list("name" = samp_name, "ID"=samp_id, "xts_obj"=xts_object, "daily_obj"=daily,
                 "weekly_obj"=weekly, "monthly_obj"=monthly)
  return(result)
}

#input a sample name
#returns a vector labeled with sample name, and bottom, middle, top and total transitions

calc_trans<- function(samp_name,samp_obj, id){
  bottom_trans <-0
  mid_trans<-0
  top_trans<-0
  trans<-0
  count <- 0
  
  for (i in 2:length(samp_obj$subzone)) {
  previous_state <- as.character(samp_obj$subzone[i-1])
  current_state <- as.character(samp_obj$subzone[i])
  
  #print(paste(previous_state,":",current_state))
  
  
  if (previous_state == current_state) {
    count <- count+1
  }
  else{
    
    if((current_state == "bottom") || (current_state == "Bottom")){
      bottom_trans <- bottom_trans+1
      trans<- trans+1
    }
    if (current_state=="middle" || current_state == "Middle") {
      mid_trans <- mid_trans+1
      trans <- trans+1
    }
    if(current_state =="top" || current_state=="Top"){
      top_trans <- top_trans+1
      trans <- trans+1
    }
  }
  }
  
  result <- c(samp_name,id,bottom_trans,mid_trans,top_trans,trans)
  return(result)
  
}

calc_trans_period<- function(samp_name, daily_indexed, raw_table,freq, day_offset){
  result <- data.frame()
  
  for (i in 2:(length(daily_indexed))){
    curr_day <- raw_table[paste0(index(daily_indexed)[i-1],"/",index(daily_indexed)[i])]
    curr_day_trans <- calc_trans(paste0(samp_name,".",index(daily_indexed)[i-1]),curr_day, samp_name)
    result <- rbind(result,curr_day_trans)
    }
  colnames(result) <- c("sample","ID","bottom","mid","top","total")
  return(result)
}
```

```{r my calc trans duration function}

calc_trans_duration<- function(samp_name,samp_obj, id){
  bottom_trans <-0
  mid_trans<-0
  top_trans<-0
  trans<-0
  count <- 0
  bottom_time <- 0 
  mid_time <- 0
  top_time <- 0
  
  for (i in 2:length(samp_obj$subzone)) {
  previous_state <- as.character(samp_obj$subzone[i-1])
  current_state <- as.character(samp_obj$subzone[i])
  previous_time <- index(samp_obj[i-1])
  current_time <- index(samp_obj[i])
  
  #print(paste(previous_state,":",current_state))
  
  
  if (previous_state == current_state) {
    count <- count+1
  }
  else{
    
    if((previous_state == "bottom") || (previous_state == "Bottom")){
      bottom_trans <- bottom_trans+1
      trans<- trans+1
      bottom_time <- bottom_time + difftime(current_time, previous_time,units="secs")
    }
    if (previous_state=="middle" || previous_state == "Middle") {
      mid_trans <- mid_trans+1
      trans <- trans+1
      mid_time <- mid_time + difftime(current_time, previous_time, units="secs")
    }
    if(previous_state =="top" || previous_state=="Top"){
      top_trans <- top_trans+1
      trans <- trans+1
      top_time <- top_time + difftime(current_time,previous_time,units="secs")
    }
  }
  }
  
  result <- c(samp_name,id,bottom_trans,mid_trans,top_trans,trans,bottom_time,mid_time,top_time)
  #colnames(result) <- c("sample_name","ID","bottom_trans","middle_trans","top_trans","total_trans","bottom_sec","mid_sec","top_sec")
  return(result)
  
}

calc_trans_period_duration<- function(samp_name, daily_indexed, raw_table,freq,day_offset ){
  result <- data.frame()
  
  for (i in 2:(length(daily_indexed))){
    curr_day <- raw_table[paste0(index(daily_indexed)[i-1],"/",index(daily_indexed)[i])]
    curr_day_trans <- calc_trans_duration(paste0(samp_name,".",freq,".",(i+day_offset)),curr_day, samp_name)
    result <- rbind(result,curr_day_trans)
    }
  colnames(result) <- c("sample_name","ID","bottom_trans","middle_trans","top_trans","total_trans","bottom_sec","mid_sec","top_sec")
  return(result)
}
```

```{r calculate duration spent in each zone}

calc_zone_duration <- function(samp_name, id, samp_obj){
  bottom_time <- 0
  mid_time <- 0 
  top_time <- 0

  current_zone <- ""
  current_datetime <- ""
  next_datetime <- ""

  for(i in 1:(length(index(samp_obj))-1)){

    current_zone <- as.character(samp_obj[i]$subzone)

    #this is measured in seconds
    sec_in_zone_i <- as.numeric(index(samp_obj[i+1]$accessdate)) - as.numeric(index(samp_obj[i]$accessdate))

    if(current_zone == "bottom"){
      bottom_time <- bottom_time + sec_in_zone_i
      sec_in_zone_i <- 0
    } else if(current_zone == "middle"){
      mid_time <- mid_time + sec_in_zone_i
      sec_in_zone_i <- 0
    } else if(current_zone == "top"){
      top_time <- top_time + sec_in_zone_i
      sec_in_zone_i <- 0
    }

  }

  return(c(samp_name, id, as.numeric(bottom_time), as.numeric(mid_time), as.numeric(top_time)))

}

```


```{r calculate time in zone for each day of study}
  
  calc_zone_duration_daily <- function(bird_id, bird_trans){

    end_of_series <- as.POSIXct(bird_trans$access)
    first_day <- as.POSIXct(bird_trans$access[1,])
    last_day <- as.POSIXct(bird_trans$access[end_of_series,])
    series <- seq(as.Date(first_day,format="%Y-%m-%d"), as.Date(last_day,format="%Y-%m-%d"), by="days")

    daily_sum_table <- data.frame()

    for(i in 1:length(series)){

      one_day <- subset(bird_trans, format(bird_trans$access, "%Y-%M-%D") > format(bird_trans$access[i], "%Y-%M-%D") & format(bird_trans$access, "%Y-%M-%D") < bird_trans$access[i+1])

      daily_sum_table <- rbind(daily_sum_table,calc_zone_duration(format(bird_trans$access[i], "%Y-%M-%D"), bird_id, one_day))
    }

    return(bird_id, daily_sum_table)
  }
```

```{r calculate duration spent in each zone}

calc_zone_duration <- function(samp_obj){
  bottom_time <- 0
  mid_time <- 0 
  top_time <- 0

  current_zone <- ""
  current_datetime <- ""
  next_datetime <- ""

  for(i in 1:(length(index(samp_obj))-1)){

    current_zone <- as.character(samp_obj$subzone[i])

    #this is measured in seconds
    min_in_zone_i <- as.numeric(samp_obj$accessdate[i] - samp_obj$accessdate[i+1])

    if(current_zone == "bottom"){
      bottom_time <- bottom_time + min_in_zone_i
      min_in_zone_i <- 0
    } else if(current_zone == "middle"){
      mid_time <- mid_time + min_in_zone_i
      min_in_zone_i <- 0
    } else if(current_zone == "top"){
      top_time <- top_time + min_in_zone_i
      min_in_zone_i <- 0
    }

  }

  return(c(as.numeric(bottom_time), as.numeric(mid_time), as.numeric(top_time)))

}

```


```{r calculate time in zone for each day of study}
  
  calc_zone_duration_daily <- function(bird_trans){

    first_day <- as.Date(head(bird_trans$accessdate,n=1))
    last_day <- as.Date(tail(bird_trans$accessdate,n=1))

    if(first_day < last_day){
      series <- seq(first_day,last_day, by="days")
    } else if(last_day< first_day) {
      series <- seq(last_day,first_day, by="days")
    } else {
      print("error")
      exit(1)
    }
    

    daily_sum_table <- data.frame()

    for(i in 1:length(series)){

      one_day <- subset(bird_trans,( as.Date(bird_trans$accessdate) >= as.Date(series[i])))
      one_day <- subset(one_day, one_day$accessdate < as.Date(series[i+1]))

      one_day_min <- calc_zone_duration(one_day)


      daily_sum_table <- rbind(series[i], one_day_min)
    }

    return(daily_sum_table)
  }
```


for(i in 1:length(record)-1){
  print(paste(record[i,]$subzone," : ", record[i+1,]$subzone))
}

```{r function to clean data from duplicate reads}
identify_duplicate_records <- function(records){
  records$duplicate <- rep(0, length(records$subzone))
  records <- records[order(records$accessdate),]
  
  for(i in 3:length(records$subzone)){

    primary <- records[i-2,]
    secondary <- records[i-1,]
    tertiary <- records[i,]
    #print(primary)

    #print(paste(primary$subzone," : ",secondary$subzone))
  
  
    #check if primary zone is same as secondary zone
    if(length(unique(c(primary$subzone,secondary$subzone,tertiary$subzone)))!=3){
      if(primary$subzone != secondary$subzone){
        records[[i-2,"duplicate"]] <- 1
      } else if(secondary$subzone != tertiary$subzone){
        records[[i-1,"duplicate"]] <- 1
      }
    }

  }
  return(records)
}

```


```{r infill time to 1 second observations}
infill_time <- function(incomplete_time){

  complete_table <- data.frame()

  for(i in 2:length(incomplete_time$accessdate)){

    primary <- incomplete_time[i-1,]
    secondary <- incomplete_time[i,]

    primary_time <- ymd_hms(primary$accessdate)
    primary_zone <- primary$subzone

    secondary_time <- ymd_hms(secondary$accessdate)
    secondary_zone <- secondary$subzone

    if(! difftime(secondary_time, primary_time, units="secs") == 1){
      infill_time <- seq(primary_time,secondary_time-1, by='secs')
      infill_zone <- rep(primary_zone, length(infill_time))
      new_data <- cbind(infill_time, infill_zone)
    }
    complete_table <- rbind(complete_table, new_data)
  }
  return(complete_table)
}
```

```{r from Keni's data}
# from Analyis.R generated by Keni
 getTimeBudget <- function(data,selectedIDs) {
  columns = c("tag","Standing","Walking","Rest","Feeding") 
  TBS = data.frame(matrix(nrow = 0, ncol = length(columns))) 
  colnames(TBS) = columns
  for (tagidx in 1:length(selectedIDs)) {
    i <- which(data$tag == selectedIDs[tagidx])
 
     TBStag<- data.frame(tag=data$tag[i],x = data$x[i], y = data$y[i], t = (data$t2[i] - data$t1[i]) / 1000 / 60 / 60, act=data$activity[i])
     tag<-selectedIDs[tagidx]
     TB1<-sum(TBStag[which(TBStag$act == 1),]$t)/sum(TBStag$t)
    
     TB2<-sum(TBStag[which(TBStag$act == 2),]$t)/sum(TBStag$t)
     
     TB3<-sum(TBStag[which(TBStag$act == 3),]$t)/sum(TBStag$t)
     
     TB4<-sum(TBStag[which(TBStag$act == 4),]$t)/sum(TBStag$t)
     TBS[tagidx,]<-c(tag,TB1,TB2,TB3,TB4)
     
  }
 
  return(TBS)
  
}
```

## Import Room 2

```{r generate transition tables for room 2}

library(xts)
library(lubridate)
library(tidyverse)
library(tidyr)
library(dplyr)
library(tsibble)


room_2 <- read.csv("../data/DK20-03-RFID-R2-febmay-080423.csv")

bird_ids_room_2 <- unique(room_2$tagname)
bird_ids_room_2 <- na.trim(sort(bird_ids_room_2))

room_2["DateTime"] <- as.POSIXct(room_2$access, origin="1970-01-01", tz="GMT")

print("what makes up subzone col")
unique(room_2$subzone)

room_2$subzone[room_2$subzone == "Bottom"] <- "bottom"
room_2$subzone[room_2$subzone == "Middle"] <- "middle"
room_2$subzone[room_2$subzone == "Top"] <- "top"

#65475
print("what makes up subzone col")
unique(room_2$subzone)

print("how many NAs in DateTime and Subzone")
sum(is.na(room_2$DateTime))
sum(is.na(room_2$subzone))

room_2$accessdate <- dmy_hms(room_2$accessdate)

# find the five number summary to determine the median interval in seconds of each reading to determine the proper sampling interval
# mean of the median times for room 2 is 9 minutes so move up to 10 minutes
# mean of the mean times for room 2 is 38 minutes so move down to every 30 minutes
room_2_summary <- room_2 |> nest(data = - tagname) |> 
 na.exclude() |>
 mutate(id_dupes = map(data ,~identify_duplicate_records(.x))) |>
 mutate(cleaned = map(id_dupes, ~.x[! .x$duplicate == 1,])) |>
 mutate(tsibble = map(cleaned, ~tsibble(datetime = ymd_hms(.x$accessdate), value = .x$subzone, index = datetime) )) |>
 mutate(intervals_s = map(tsibble, ~ as.numeric(difftime(.x$datetime[1:(length(.x$datetime)-1)], .x$datetime[2:length(.x$datetime)],units='secs') ))) |>
 mutate(summary = map(intervals_s, ~summary(.x))) |>
 mutate(median = map(summary, ~.x[3])) |>
 mutate(mean = map(summary, ~.x[4])) |>
 unnest(c(median,mean))

# 
room_2_struct <- room_2 |> nest(data = - tagname) |> 
 na.exclude() |>
 mutate(id_dupes = map(data ,~identify_duplicate_records(.x))) |>
 mutate(cleaned = map(id_dupes, ~.x[! .x$duplicate == 1,])) |>
 # How long does it take to infill one dataframe? is it too long?
 mutate(tsibble = map(cleaned, ~tsibble(datetime = ymd_hms(.x$accessdate), value = .x$subzone, index = datetime) ))
 
attr(room_2_struct$tsibble, 'interval') <- new_interval(minute = 10)
#TODO need to set the start time for each series to a nice 

 room_2_regular <- room_2_struct |>
 mutate(perSec = map(tsibble, ~ fill_gaps(.x))) |>
 mutate(summary = map(tsibble, ~summary(.x))) |>
 unnest(summary)


room_2_struct <- room_2_struct |>
  mutate(sampled = map(perSec, ~ na.locf(.x)))

#tmp <- tsibble(datetime = ymd_hms(room_2_struct$cleaned[[1]]$accessdate), value = room_2_struct$cleaned[[1]]$subzone, index = datetime) %>% fill_gaps() %>% na.locf() %>% fill_gaps() %>% na.locf()
  
  

 


map(data, ~ .x |> 
                                 track_resample(rate = hours(4), tolerance = minutes(10)) |>
                                 steps_by_burst()))


#generate list of XTS objects 
reslist_room_2 <- list()
for(i in 1:length(bird_ids_room_2)){
  
  res <- sep_bird_id_xts(samp_name="room 2",cage_obj =room_2, samp_id = bird_ids_room_2[i])
  reslist_room_2[[i]] <- res
}

cutoff_room_2 <- data.frame()
for(i in 1:length(reslist_room_2)){
  id <- reslist_room_2[[i]]$ID
  top <- index(head(reslist_room_2[[i]]$xts_obj))[1]
  bottom <- index(tail(reslist_room_2[[i]]$xts_obj))[6]
  rec <- cbind(id,as.character(top),as.character(bottom))
  cutoff_room_2 <- rbind(cutoff_room_2,rec)
  
}

#head
cutoff_room_2[order(cutoff_room_2$V2),]
#tail
cutoff_room_2[order(cutoff_room_2$V3),]



#remove <- c("6910","6914","9005")
remove <- c("6910","6966","6914")
bird_ids_room_2_new <- bird_ids_room_2 [! bird_ids_room_2  %in% remove ]
#generate list of the first 10 truncated XTS objects
reslist2_room_2 <- list()
for(i in 1:length(bird_ids_room_2_new)){
  res <- sep_bird_id_period(samp_name="room 2",cage_obj =room_2, samp_id = bird_ids_room_2_new[i],cutoff = "2021-03-09 T20:00:00/2021-05-06 T23:00:00")
  reslist2_room_2[[i]] <- res
}

#find wholly non-na daily timeset, to be able to feed into the transcalc
big_table_room_2 <- reslist2_room_2[[1]]$daily_obj
for(i in 2:length(reslist2_room_2)){
  current <- reslist2_room_2[[i]]$daily_obj
  colnames(current) <- as.character(reslist2_room_2[[i]]$ID)
  big_table_room_2 <- cbind(big_table_room_2,current)
}
print("How many NAs in big_table_room_2")
print(sum(is.na(big_table_room_2)))
```

## Import Room 3

```{r import room 3}
library(xts)
library(tidyverse)

room_3 <- read.csv("../data/DK20-03-RFID-R3-febmay-080423.csv") %>% na.exclude()

bird_ids_room_3 <- unique(room_3$tagname)
bird_ids_room_3 <- na.trim(sort(bird_ids_room_3))

room_3["DateTime"] <- as.POSIXct(room_3$access, origin="1970-01-01", tz="GMT")

print("what makes up subzone col")
unique(room_3$subzone)

room_3$subzone[room_3$subzone == "Bottom"] <- "bottom"
room_3$subzone[room_3$subzone == "Middle"] <- "middle"
room_3$subzone[room_3$subzone == "Top"] <- "top"


print("what makes up subzone col")
unique(room_3$subzone)

print("how many NA's are in Datetime and Subzone")
sum(is.na(room_3$DateTime))
sum(is.na(room_3$subzone))

room_3 <- room_3[!is.na(room_3$DateTime),]

print("how many NA's are in Datetime and Subzone")
sum(is.na(room_3$DateTime))
sum(is.na(room_3$subzone))


#generate list of XTS objects 
reslist_room_3 <- list()
for(i in 1:length(bird_ids_room_3)){
  
  res <- sep_bird_id_xts(samp_name="room_3",cage_obj =room_3, samp_id = bird_ids_room_3[i])
  reslist_room_3[[i]] <- res
}



cutoff_room_3 <- data.frame()
for(i in 1:length(reslist_room_3)){
  id <- reslist_room_3[[i]]$ID
  top <- index(head(reslist_room_3[[i]]$xts_obj))[1]
  bottom <- index(tail(reslist_room_3[[i]]$xts_obj))[6]
  rec <- cbind(id,as.character(top),as.character(bottom))
  cutoff_room_3 <- rbind(cutoff_room_3,rec)
  
}

#head
cutoff_room_3[order(cutoff_room_3$V2),]
#tail
cutoff_room_3[order(cutoff_room_3$V3),]


#remove <- c("6998")
remove <- c("6915","9008","6912","6987","6948","6953","6879","6968","9029")
bird_ids_room_3_new <- bird_ids_room_3 [! bird_ids_room_3  %in% remove ]
#generate list of the first 10 truncated XTS objects
reslist2_room_3 <- list()
for(i in 1:length(bird_ids_room_3_new)){
  res <- sep_bird_id_period(samp_name="room 3",cage_obj=room_3, samp_id =bird_ids_room_3_new[i],cutoff = "2021-03-09 T20:00:00/2021-05-06 T23:00:00")
  #print(res)

  reslist2_room_3[[i]] <- res
}



#find wholly non-na daily timeset, to be able to feed into the transcalc
big_table_room_3 <- reslist2_room_3[[1]]$daily_obj
for(i in 2:length(reslist2_room_3)){
  current <- reslist2_room_3[[i]]$daily_obj
  big_table_room_3 <- cbind(big_table_room_3,current)
}
print("how many NA's are in big_table_room_3")
print(sum(is.na(big_table_room_3)))
```

## Import Room 8

```{r import Room 8}
library(xts)

room_8 <- read.csv("../data/DK20-03-RFID-r8-febmay-080423.csv")

bird_ids_room_8 <- na.trim(unique(room_8$tagname))
bird_ids_room_8 <- sort(bird_ids_room_8)

room_8["DateTime"] <- as.POSIXct(room_8$access, origin="1970-01-01", tz="GMT")

print("what makes up subzone col")
unique(room_8$subzone)

room_8$subzone[room_8$subzone == "Bottom"] <- "bottom"
room_8$subzone[room_8$subzone == "middle"] <- "middle"
room_8$subzone[room_8$subzone == "Top"] <- "top"
room_8 <-subset(room_8, subzone!="test")

print("what makes up subzone col")
unique(room_8$subzone)

print("how many NA's in Datetime and Subzone")
sum(is.na(room_8$DateTime))
sum(is.na(room_8$subzone))

#generate list of XTS objects 
reslist_room_8 <- list()
for(i in 1:length(bird_ids_room_8)){
  
  res <- sep_bird_id_xts(samp_name="room 8",cage_obj =room_8, samp_id = bird_ids_room_8[i])
  reslist_room_8[[i]] <- res
}

cutoff_room_8 <- data.frame()
for(i in 1:length(reslist_room_8)){
  id <- reslist_room_8[[i]]$ID
  top <- index(head(reslist_room_8[[i]]$xts_obj))[1]
  bottom <- index(tail(reslist_room_8[[i]]$xts_obj))[6]
  rec <- cbind(id,as.character(top),as.character(bottom))
  cutoff_room_8 <- rbind(cutoff_room_8,rec)
  
}

#head
cutoff_room_8[order(cutoff_room_8$V2),]
#tail
cutoff_room_8[order(cutoff_room_8$V3),]

remove <-c("6949","6936","6974","9009","9011","6995")
bird_ids_room_8_new <- bird_ids_room_8 [! bird_ids_room_8  %in% remove ]
#generate list of the first 10 truncated XTS objects
reslist2_room_8 <- list()
for(i in 1:length(bird_ids_room_8_new)){
  res <- sep_bird_id_period(samp_name="room 8",cage_obj =room_8, samp_id = bird_ids_room_8_new[i],cutoff = "2021-03-09 T20:00:00/2021-05-06 T23:00:00")
  reslist2_room_8[[i]] <- res
}

#find wholly non-na daily timeset, to be able to feed into the transcalc
big_table_room_8 <- reslist2_room_8[[1]]$daily_obj
for(i in 2:length(reslist2_room_8)){
  current <- reslist2_room_8[[i]]$daily_obj
  big_table_room_8 <- cbind(big_table_room_8,current)
}
print("how many NA's in big_table_room_8")
print(sum(is.na(big_table_room_8)))
```

## Import Room 11

```{r import Room 11}
library(xts)

room_11 <- read.csv("../data/DK20-03-RFID-R11-febmay-080423.csv")

bird_ids_room_11 <- na.trim(unique(room_11$tagname))
bird_ids_room_11 <- sort(bird_ids_room_11)

room_11 <- room_11[order(room_11$access),] 

room_11["DateTime"] <- as.POSIXct(room_11$access, origin="1970-01-01", tz="GMT")

print("what composes the subzone column")
unique(room_11$subzone)

room_11$subzone[room_11$subzone == "M"] <- "middle"
room_11$subzone[room_11$subzone == "B"] <- "bottom"
room_11$subzone[room_11$subzone == "T"] <- "top"

print("what composes the subzone column")
unique(room_11$subzone)

print("how many NA's in the DateTime col")
sum(is.na(room_11$DateTime))

room_11 <- room_11[!is.na(room_11$DateTime),]

print("how many NA's in the Datetime col")
sum(is.na(room_11$DateTime))

#generate list of XTS objects 
reslist_room_11 <- list()
for(i in 1:length(bird_ids_room_11)){
  
  res <- sep_bird_id_xts(samp_name="room 11",cage_obj =room_11, samp_id = bird_ids_room_11[i])
  reslist_room_11[[i]] <- res
}

# index 10 is an error right now, how can we fix na value

remove <- c("6888")

cutoff_room_11 <- data.frame()
for(i in 1:length(reslist_room_11)){
  print(i)
  id <- reslist_room_11[[i]]$ID
  if(id %in% remove){
  } else{
    top <- index(head(reslist_room_11[[i]]$xts_obj))[1]
    bottom <- index(tail(reslist_room_11[[i]]$xts_obj))[6]
    rec <- cbind(id,as.character(top),as.character(bottom))
    cutoff_room_11 <- rbind(cutoff_room_11,rec)
  }
}

#head
cutoff_room_11[order(cutoff_room_11$V2),]
#tail
cutoff_room_11[order(cutoff_room_11$V3),]

 

remove <- c("6888","6868","6880","6881","6893","6892", "6894","6862","6898","6882","6899","6887","6896","6889","6895","6885","6900","6897","6891","6884","6906","6920","6954","6991","6930","9059","9060")
bird_ids_room_11_new <- bird_ids_room_11 [! bird_ids_room_11  %in% remove ]
#generate list of the first 10 truncated XTS objects
reslist2_room_11 <- list()
for(i in 1:length(bird_ids_room_11_new)){
  res <- sep_bird_id_period(samp_name="room 11",cage_obj =room_11, samp_id = bird_ids_room_11_new[i], cutoff="2021-03-09 T20:00:00/2021-05-06 T23:00:00")
  reslist2_room_11[[i]] <- res
}


#find wholly non-na daily timeset, to be able to feed into the transcalc
big_table_room_11 <- reslist2_room_11[[1]]$daily_obj
for(i in 2:length(reslist2_room_11)){
  current <- reslist2_room_11[[i]]$daily_obj
  big_table_room_11 <- cbind(big_table_room_11,current)
}
print("Na's in big_table_room_11")
print(sum(is.na(big_table_room_11)))
print("top of big_table_room_11")
print(head(big_table_room_11))
```

# Intra-Bird Analysis With All Rooms

```{r }
trans_reslist_room_2 <- list()

for(i in 1:length(reslist2_room_2)){
  
  daily_trans_table <- calc_trans_period(reslist2_room_2[[i]]$ID,reslist2_room_2[[i]]$daily_obj,reslist2_room_2[[i]]$xts_obj,"d", 0)
  weekly_trans_table <- calc_trans_period(reslist2_room_2[[i]]$ID,reslist2_room_2[[i]]$weekly_obj,reslist2_room_2[[i]]$xts_obj,"w", 0)
  monthly_trans_table <- calc_trans_period(reslist2_room_2[[i]]$ID,reslist2_room_2[[i]]$monthly_obj,reslist2_room_2[[i]]$xts_obj,"m",0)
    
  result <- list("ID"=reslist2_room_2[[i]]$ID,"daily"=daily_trans_table, "weekly"=weekly_trans_table,"monthly"=monthly_trans_table, "raw"=reslist2_room_2[[i]]$xts_obj)
  trans_reslist_room_2[[i]] <- result
}

room_2_daily <- data.frame()
room_2_weekly <- data.frame()
room_2_monthly <- data.frame()
#TODO select sample as opposed to ID for intra bird comparison (alpha eq)
for(item in trans_reslist_room_2){
  room_2_daily <- rbind(room_2_daily, item$daily[c("sample","bottom","mid","top","total")])
  room_2_weekly <- rbind(room_2_weekly, item$weekly[c("sample","bottom","mid","top","total")])
  room_2_monthly <- rbind(room_2_monthly, item$monthly[c("sample","bottom","mid","top","total")])
}

# check to make sure only one bird is selected
print("check that the id and RFID tag are unique for each item entry")
#this is following up with the issues of the intra-bird comparisons
for(item in trans_reslist_room_2){
  print(paste(unique(item$raw$Tagnumber)," ",unique(item$raw$tagname)))
  #print(item)
}

trans_reslist_room_3 <- list()
for(i in 1:length(reslist2_room_3)){
  
  daily_trans_table <- calc_trans_period(reslist2_room_3[[i]]$ID,reslist2_room_3[[i]]$daily_obj,reslist2_room_3[[i]]$xts_obj,"d",0)
  weekly_trans_table <- calc_trans_period(reslist2_room_3[[i]]$ID,reslist2_room_3[[i]]$weekly_obj,reslist2_room_3[[i]]$xts_obj,"w",0)
  monthly_trans_table <- calc_trans_period(reslist2_room_3[[i]]$ID,reslist2_room_3[[i]]$monthly_obj,reslist2_room_3[[i]]$xts_obj,"m",0)
    
  result <- list("ID"=reslist2_room_3[[i]]$ID,"daily"=daily_trans_table, "weekly"=weekly_trans_table,"monthly"=monthly_trans_table, "raw"=reslist2_room_3[[i]]$xts_obj)
  trans_reslist_room_3[[i]] <- result
}

room_3_daily <- data.frame()
room_3_weekly <- data.frame()
room_3_monthly <- data.frame()
#TODO select sample as opposed to ID for intra bird comparison (alpha eq)
for(item in trans_reslist_room_3){
  room_3_daily <- rbind(room_3_daily, item$daily[c("sample","bottom","mid","top","total")])
  room_3_weekly <- rbind(room_3_weekly, item$weekly[c("sample","bottom","mid","top","total")])
  room_3_monthly <- rbind(room_3_monthly, item$monthly[c("sample","bottom","mid","top","total")])
}

# check to make sure only one bird is selected
print("check that the id and RFID tag are unique for each item entry")
#this is following up with the issues of the intra-bird comparisons
for(item in trans_reslist_room_3){
  print(paste(unique(item$raw$Tagnumber)," ",unique(item$raw$tagname)))
  #print(item)
}

trans_reslist_room_8 <- list()

for(i in 1:length(reslist2_room_8)){
  
  daily_trans_table <- calc_trans_period(reslist2_room_8[[i]]$ID,reslist2_room_8[[i]]$daily_obj,reslist2_room_8[[i]]$xts_obj,"d",0)
  weekly_trans_table <- calc_trans_period(reslist2_room_8[[i]]$ID,reslist2_room_8[[i]]$weekly_obj,reslist2_room_8[[i]]$xts_obj,"w",0)
  monthly_trans_table <- calc_trans_period(reslist2_room_8[[i]]$ID,reslist2_room_8[[i]]$monthly_obj,reslist2_room_8[[i]]$xts_obj,"m",0)
    
  result <- list("ID"=reslist2_room_8[[i]]$ID,"daily"=daily_trans_table, "weekly"=weekly_trans_table,"monthly"=monthly_trans_table, "raw"=reslist2_room_8[[i]]$xts_obj)
  trans_reslist_room_8[[i]] <- result
}

room_8_daily <- data.frame()
room_8_weekly <- data.frame()
room_8_monthly <- data.frame()
#TODO select sample as opposed to ID for intra bird comparison (alpha eq)
for(item in trans_reslist_room_8){
  room_8_daily <- rbind(room_8_daily, item$daily[c("sample","bottom","mid","top","total")])
  room_8_weekly <- rbind(room_8_weekly, item$weekly[c("sample","bottom","mid","top","total")])
  room_8_monthly <- rbind(room_8_monthly, item$monthly[c("sample","bottom","mid","top","total")])
}

# check to make sure only one bird is selected
print("check that the id and RFID tag are unique for each item entry")
#this is following up with the issues of the intra-bird comparisons
for(item in trans_reslist_room_8){
  print(paste(unique(item$raw$tagnumber)," ",unique(item$raw$tagname)))
  #print(item)
}

trans_reslist_room_11 <- list()

for(i in 1:length(reslist2_room_11)){
  
  daily_trans_table <- calc_trans_period(reslist2_room_11[[i]]$ID,reslist2_room_11[[i]]$daily_obj,reslist2_room_11[[i]]$xts_obj,"d")
  weekly_trans_table <- calc_trans_period(reslist2_room_11[[i]]$ID,reslist2_room_11[[i]]$weekly_obj,reslist2_room_11[[i]]$xts_obj,"w")
  monthly_trans_table <- calc_trans_period(reslist2_room_11[[i]]$ID,reslist2_room_11[[i]]$monthly_obj,reslist2_room_11[[i]]$xts_obj,"m")
    
  result <- list("ID"=reslist2_room_11[[i]]$ID,"daily"=daily_trans_table, "weekly"=weekly_trans_table,"monthly"=monthly_trans_table, "raw"=reslist2_room_11[[i]]$xts_obj)
  trans_reslist_room_11[[i]] <- result
}

room_11_daily <- data.frame()
room_11_weekly <- data.frame()
room_11_monthly <- data.frame()
#TODO select sample as opposed to ID for intra bird comparison (alpha eq)
for(item in trans_reslist_room_11){
  room_11_daily <- rbind(room_11_daily, item$daily[c("sample","bottom","mid","top","total")])
  room_11_weekly <- rbind(room_11_weekly, item$weekly[c("sample","bottom","mid","top","total")])
  room_11_monthly <- rbind(room_11_monthly, item$monthly[c("sample","bottom","mid","top","total")])
}

# check to make sure only one bird is selected
print("check that the id and RFID tag are unique for each item entry")
#this is following up with the issues of the intra-bird comparisons
for(item in trans_reslist_room_11){
  print(paste(unique(item$raw$tagnumber)," ",unique(item$raw$tagname)))
  #print(item)
}

# w <- 0
# for(item in trans_reslist_room_2){
#   w <- w +1
#   print(w)
# }
# w <- 0
# for(item in trans_reslist_room_3){
#   w <- w +1
#   print(w)
# }
# w <- 0
# for(item in trans_reslist_room_8){
#   w <- w +1
#   print(w)
# }
# w <- 0
# for(item in trans_reslist_room_11){
#   w <- w +1
#   print(w)
# }
#write.csv(room_2_daily,"room_2_daily_intra.csv",row.names = F)
#write.csv(room_2_weekly,"room_2_weekly_intra.csv",row.names = F)
#write.csv(room_2_monthly,"room_2_monthly_intra.csv",row.names = F)

```